/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Album {
  'id' : string,
  'coverImageUrl' : string,
  'title' : string,
  'tracklist' : Array<Track>,
  'totalSupply' : bigint,
  'artist' : string,
  'collectionName' : string,
}
export interface MarketListing {
  'seller' : Principal,
  'editionId' : bigint,
  'price' : bigint,
}
export interface Release {
  'album' : Album,
  'floorPrice' : bigint,
  'isActive' : boolean,
  'lastSoldPrice' : bigint,
  'mintedCount' : bigint,
  'ownersCount' : bigint,
  'mintOpenTime' : bigint,
}
export interface Track { 'title' : string, 'duration' : bigint }
export interface _SERVICE {
  'addAlbum' : ActorMethod<[Album], undefined>,
  'addRelease' : ActorMethod<[Release], undefined>,
  'getAlbumById' : ActorMethod<[string], [] | [Album]>,
  'getAlbums' : ActorMethod<[], Array<Album>>,
  'getMarketListings' : ActorMethod<[], Array<MarketListing>>,
  'getReleases' : ActorMethod<[], Array<Release>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];