/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Track = IDL.Record({ 'title' : IDL.Text, 'duration' : IDL.Nat });
export const Album = IDL.Record({
  'id' : IDL.Text,
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'tracklist' : IDL.Vec(Track),
  'totalSupply' : IDL.Nat,
  'artist' : IDL.Text,
  'collectionName' : IDL.Text,
});
export const AddPackInput = IDL.Record({
  'id' : IDL.Text,
  'coverImageUrl' : IDL.Text,
  'setName' : IDL.Text,
  'ownerPrincipal' : IDL.Principal,
  'totalSupply' : IDL.Nat,
  'releaseId' : IDL.Text,
  'serialNumber' : IDL.Nat,
  'packCount' : IDL.Nat,
});
export const Release = IDL.Record({
  'album' : Album,
  'floorPrice' : IDL.Nat,
  'isActive' : IDL.Bool,
  'lastSoldPrice' : IDL.Nat,
  'mintedCount' : IDL.Nat,
  'ownersCount' : IDL.Nat,
  'mintOpenTime' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateTcgCardInput = IDL.Record({
  'cardName' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'isActive' : IDL.Bool,
  'setId' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'rarity' : IDL.Text,
  'cardNumber' : IDL.Text,
  'isSupported' : IDL.Bool,
});
export const TcgCard = IDL.Record({
  'id' : IDL.Nat,
  'cardName' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'isActive' : IDL.Bool,
  'setId' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'rarity' : IDL.Text,
  'cardNumber' : IDL.Text,
  'isSupported' : IDL.Bool,
});
export const CreateTcgCategoryInput = IDL.Record({
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
});
export const TcgCategory = IDL.Record({
  'id' : IDL.Nat,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
});
export const CreateTcgSetInput = IDL.Record({
  'setCode' : IDL.Text,
  'coverImageUrl' : IDL.Text,
  'setName' : IDL.Text,
  'featured' : IDL.Bool,
  'tcgCategory' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'slug' : IDL.Text,
  'isActive' : IDL.Bool,
  'cardCount' : IDL.Opt(IDL.Nat),
  'releaseYear' : IDL.Nat,
});
export const TcgSet = IDL.Record({
  'id' : IDL.Nat,
  'setCode' : IDL.Text,
  'coverImageUrl' : IDL.Text,
  'setName' : IDL.Text,
  'featured' : IDL.Bool,
  'tcgCategory' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'slug' : IDL.Text,
  'isActive' : IDL.Bool,
  'cardCount' : IDL.Opt(IDL.Nat),
  'releaseYear' : IDL.Nat,
});
export const WalletActivityType = IDL.Variant({
  'mintCost' : IDL.Null,
  'deposit' : IDL.Null,
  'auctionPayout' : IDL.Null,
});
export const WalletActivity = IDL.Record({
  'status' : IDL.Variant({ 'pending' : IDL.Null, 'confirmed' : IDL.Null }),
  'activityType' : WalletActivityType,
  'btcAmountE8s' : IDL.Nat,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const BondingCurveState = IDL.Record({
  'startingPrice' : IDL.Float64,
  'clipId' : IDL.Text,
  'currentPrice' : IDL.Float64,
  'totalSupply' : IDL.Nat,
  'nextPrice' : IDL.Float64,
  'soldOut' : IDL.Bool,
  'priceIncrementFactor' : IDL.Float64,
  'copiesMinted' : IDL.Nat,
});
export const CollectibleMediaType = IDL.Variant({
  'video' : IDL.Null,
  'photo' : IDL.Null,
});
export const Collectible = IDL.Record({
  'id' : IDL.Text,
  'setName' : IDL.Text,
  'title' : IDL.Text,
  'creator' : IDL.Text,
  'typeSupply' : IDL.Nat,
  'editionNumber' : IDL.Nat,
  'ownerPrincipal' : IDL.Principal,
  'mintDate' : IDL.Text,
  'totalSupply' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'releaseId' : IDL.Text,
  'mediaType' : CollectibleMediaType,
  'rarity' : IDL.Text,
  'packId' : IDL.Text,
  'openedAt' : IDL.Int,
});
export const PackStatus = IDL.Variant({
  'opened' : IDL.Null,
  'sealed' : IDL.Null,
});
export const Pack = IDL.Record({
  'id' : IDL.Text,
  'status' : PackStatus,
  'coverImageUrl' : IDL.Text,
  'setName' : IDL.Text,
  'ownerPrincipal' : IDL.Principal,
  'createdAt' : IDL.Int,
  'totalSupply' : IDL.Nat,
  'releaseId' : IDL.Text,
  'serialNumber' : IDL.Nat,
  'packCount' : IDL.Nat,
  'collectibleId' : IDL.Opt(IDL.Text),
  'openedAt' : IDL.Opt(IDL.Int),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const VideoClipSort = IDL.Variant({
  'top' : IDL.Null,
  'trending' : IDL.Null,
  'newest' : IDL.Null,
});
export const VideoClip = IDL.Record({
  'clip_id' : IDL.Text,
  'like_timestamps' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Int)),
  'title' : IDL.Opt(IDL.Text),
  'hashtags' : IDL.Vec(IDL.Text),
  'preview_loop_url' : IDL.Text,
  'like_count' : IDL.Nat,
  'likes_last_6_hours' : IDL.Nat,
  'likes_last_24_hours' : IDL.Nat,
  'timestamp' : IDL.Int,
  'likes_last_hour' : IDL.Nat,
  'explicit_flag' : IDL.Bool,
  'creator_principal_id' : IDL.Principal,
  'video_file_url' : IDL.Text,
});
export const ListingStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'sold' : IDL.Null,
});
export const Listing = IDL.Record({
  'id' : IDL.Nat,
  'status' : ListingStatus,
  'clipId' : IDL.Text,
  'totalEditions' : IDL.Nat,
  'sellerPrincipal' : IDL.Principal,
  'listPriceUsd' : IDL.Float64,
  'editionNumber' : IDL.Nat,
  'listedAt' : IDL.Int,
});
export const MarketCapEntry = IDL.Record({
  'clipId' : IDL.Text,
  'title' : IDL.Text,
  'previewUrl' : IDL.Text,
  'totalSupply' : IDL.Nat,
  'creatorName' : IDL.Text,
  'currentPriceUsd' : IDL.Float64,
  'copiesSold' : IDL.Nat,
  'videoUrl' : IDL.Text,
  'marketCapUsd' : IDL.Float64,
});
export const MarketListing = IDL.Record({
  'seller' : IDL.Principal,
  'editionId' : IDL.Nat,
  'price' : IDL.Nat,
});
export const EarningsSummary = IDL.Record({
  'totalBtcE8s' : IDL.Nat,
  'fromAuctionWins' : IDL.Float64,
  'fromCopySales' : IDL.Float64,
  'totalUsd' : IDL.Float64,
  'fromTradeRoyalties' : IDL.Float64,
  'transactionCount' : IDL.Nat,
});
export const PurchaseStatus = IDL.Variant({
  'pending' : IDL.Null,
  'minted' : IDL.Null,
});
export const PurchaseRecord = IDL.Record({
  'status' : PurchaseStatus,
  'clipId' : IDL.Text,
  'editionNumber' : IDL.Nat,
  'purchasedAt' : IDL.Int,
  'buyerPrincipal' : IDL.Principal,
  'pricePaid' : IDL.Float64,
  'purchaseId' : IDL.Text,
});
export const TxType = IDL.Variant({
  'mintFee' : IDL.Null,
  'secondaryTrade' : IDL.Null,
  'copySale' : IDL.Null,
});
export const TxSplit = IDL.Record({
  'principal' : IDL.Principal,
  'role' : IDL.Text,
  'usdAmount' : IDL.Float64,
  'btcAmountSimulated' : IDL.Float64,
  'btcAddress' : IDL.Text,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'clipId' : IDL.Text,
  'totalUsd' : IDL.Float64,
  'timestamp' : IDL.Int,
  'txType' : TxType,
  'splits' : IDL.Vec(TxSplit),
});
export const OfferStatus = IDL.Variant({
  'pending' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
});
export const Offer = IDL.Record({
  'id' : IDL.Nat,
  'status' : OfferStatus,
  'offerPriceUsd' : IDL.Float64,
  'listingId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'buyerPrincipal' : IDL.Principal,
});
export const ConfirmationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Deposit = IDL.Record({
  'depositId' : IDL.Text,
  'confirmationStatus' : ConfirmationStatus,
  'btcAmountE8s' : IDL.Nat,
  'txid' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const PayoutType = IDL.Variant({
  'auctionWin' : IDL.Null,
  'copySale' : IDL.Null,
  'secondaryRoyalty' : IDL.Null,
});
export const Payout = IDL.Record({
  'clipId' : IDL.Text,
  'btcAmountE8s' : IDL.Nat,
  'payoutId' : IDL.Text,
  'timestamp' : IDL.Int,
  'payoutType' : PayoutType,
});
export const UserWallet = IDL.Record({
  'walletPrincipalId' : IDL.Principal,
  'usdValueRef' : IDL.Float64,
  'btcAddress' : IDL.Text,
  'deposits' : IDL.Vec(Deposit),
  'payouts' : IDL.Vec(Payout),
  'btcBalanceE8s' : IDL.Nat,
});
export const PricePoint = IDL.Record({
  'editionNumber' : IDL.Nat,
  'timestamp' : IDL.Int,
  'salePrice' : IDL.Float64,
});
export const PriceHistorySummary = IDL.Record({
  'currentPrice' : IDL.Float64,
  'maxPrice' : IDL.Float64,
  'totalSales' : IDL.Nat,
  'minPrice' : IDL.Float64,
  'lastSaleTimestamp' : IDL.Opt(IDL.Int),
  'firstSaleTimestamp' : IDL.Opt(IDL.Int),
});
export const VideoAsset = IDL.Record({
  'owner' : IDL.Principal,
  'data' : IDL.Vec(IDL.Nat8),
  'content_type' : IDL.Text,
  'created_at' : IDL.Int,
  'asset_id' : IDL.Text,
});
export const PackOpenResult = IDL.Variant({
  'ok' : Collectible,
  'err' : IDL.Text,
});
export const UpdateTcgCardInput = IDL.Record({
  'id' : IDL.Nat,
  'cardName' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'isActive' : IDL.Bool,
  'setId' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'rarity' : IDL.Text,
  'cardNumber' : IDL.Text,
  'isSupported' : IDL.Bool,
});
export const UpdateTcgCategoryInput = IDL.Record({
  'id' : IDL.Nat,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
});
export const UpdateTcgSetInput = IDL.Record({
  'id' : IDL.Nat,
  'setCode' : IDL.Text,
  'coverImageUrl' : IDL.Text,
  'setName' : IDL.Text,
  'featured' : IDL.Bool,
  'tcgCategory' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'slug' : IDL.Text,
  'isActive' : IDL.Bool,
  'cardCount' : IDL.Opt(IDL.Nat),
  'releaseYear' : IDL.Nat,
});

export const idlService = IDL.Service({
  'acceptOffer' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'addAlbum' : IDL.Func([Album], [], []),
  'addPack' : IDL.Func([AddPackInput], [], []),
  'addRelease' : IDL.Func([Release], [], []),
  'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelListing' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'checkForNewDeposits' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'checkLikeRateLimit' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'checkMintRateLimit' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'confirmPendingDeposits' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'createCard' : IDL.Func([CreateTcgCardInput], [TcgCard], []),
  'createCategory' : IDL.Func([CreateTcgCategoryInput], [TcgCategory], []),
  'createClip' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Vec(IDL.Text), IDL.Bool],
      [IDL.Text],
      [],
    ),
  'createListing' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Float64],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'createSet' : IDL.Func([CreateTcgSetInput], [TcgSet], []),
  'declineOffer' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteCard' : IDL.Func([IDL.Nat], [], []),
  'deleteCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteSet' : IDL.Func([IDL.Nat], [], []),
  'getAlbumById' : IDL.Func([IDL.Text], [IDL.Opt(Album)], ['query']),
  'getAlbums' : IDL.Func([], [IDL.Vec(Album)], ['query']),
  'getAllCardsAdmin' : IDL.Func([], [IDL.Vec(TcgCard)], ['query']),
  'getAllCategoriesAdmin' : IDL.Func([], [IDL.Vec(TcgCategory)], ['query']),
  'getAllSetsAdmin' : IDL.Func([], [IDL.Vec(TcgSet)], ['query']),
  'getAllWalletActivity' : IDL.Func([], [IDL.Vec(WalletActivity)], []),
  'getBondingCurveState' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(BondingCurveState)],
      ['query'],
    ),
  'getBondingCurveStates' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(BondingCurveState)],
      ['query'],
    ),
  'getBtcRate' : IDL.Func([], [IDL.Float64], ['query']),
  'getCallerCollectibles' : IDL.Func([], [IDL.Vec(Collectible)], ['query']),
  'getCallerPacks' : IDL.Func([], [IDL.Vec(Pack)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCardsBySet' : IDL.Func([IDL.Nat], [IDL.Vec(TcgCard)], ['query']),
  'getCardsBySetAdmin' : IDL.Func([IDL.Nat], [IDL.Vec(TcgCard)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(TcgCategory)], ['query']),
  'getClips' : IDL.Func(
      [VideoClipSort, IDL.Bool],
      [IDL.Vec(VideoClip)],
      ['query'],
    ),
  'getClipsByHashtag' : IDL.Func([IDL.Text], [IDL.Vec(VideoClip)], ['query']),
  'getClipsForHashtag' : IDL.Func(
      [IDL.Text, VideoClipSort, IDL.Bool],
      [IDL.Vec(VideoClip)],
      ['query'],
    ),
  'getClipsWithCurveState' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(VideoClip, IDL.Opt(BondingCurveState)))],
      ['query'],
    ),
  'getCreatorClips' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(VideoClip)],
      ['query'],
    ),
  'getCurrentPrice' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getFeaturedSets' : IDL.Func([], [IDL.Vec(TcgSet)], ['query']),
  'getListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getListingsByClip' : IDL.Func([IDL.Text], [IDL.Vec(Listing)], ['query']),
  'getMarketCap' : IDL.Func([IDL.Text], [IDL.Opt(MarketCapEntry)], ['query']),
  'getMarketListings' : IDL.Func([], [IDL.Vec(MarketListing)], ['query']),
  'getMyBalance' : IDL.Func([], [IDL.Nat], []),
  'getMyEarnings' : IDL.Func([], [EarningsSummary], ['query']),
  'getMyPurchases' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
  'getMyRole' : IDL.Func([], [UserRole], ['query']),
  'getMyTransactions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getOfferHistory' : IDL.Func([IDL.Nat], [IDL.Vec(Offer)], ['query']),
  'getOffers' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Vec(Offer), 'err' : IDL.Text })],
      ['query'],
    ),
  'getOrCreateUserWallet' : IDL.Func([], [UserWallet], []),
  'getPaymentAddress' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getPokemonSets' : IDL.Func([], [IDL.Vec(TcgSet)], ['query']),
  'getPriceHistory' : IDL.Func([IDL.Text], [IDL.Vec(PricePoint)], ['query']),
  'getPriceHistoryFull' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PricePoint)],
      ['query'],
    ),
  'getPriceHistorySummary' : IDL.Func(
      [IDL.Text],
      [PriceHistorySummary],
      ['query'],
    ),
  'getReleases' : IDL.Func([], [IDL.Vec(Release)], ['query']),
  'getSetById' : IDL.Func([IDL.Nat], [IDL.Opt(TcgSet)], ['query']),
  'getSetBySlug' : IDL.Func([IDL.Text], [IDL.Opt(TcgSet)], ['query']),
  'getSets' : IDL.Func([], [IDL.Vec(TcgSet)], ['query']),
  'getSetsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(TcgSet)], ['query']),
  'getTop10ByMarketCap' : IDL.Func([], [IDL.Vec(MarketCapEntry)], ['query']),
  'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getTrendingHashtags' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getTrendingHashtagsWithHotFlag' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Bool))],
      ['query'],
    ),
  'getUserCollectibles' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Collectible)],
      ['query'],
    ),
  'getUserDepositAddress' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getUserDeposits' : IDL.Func([], [IDL.Vec(Deposit)], []),
  'getUserPacks' : IDL.Func([IDL.Principal], [IDL.Vec(Pack)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideoBlob' : IDL.Func([IDL.Text], [IDL.Opt(VideoAsset)], ['query']),
  'initBondingCurve' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : BondingCurveState, 'err' : IDL.Text })],
      [],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeClip' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'makeOffer' : IDL.Func(
      [IDL.Nat, IDL.Float64],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'openPack' : IDL.Func([IDL.Text], [PackOpenResult], []),
  'processClipMint' : IDL.Func([IDL.Principal], [IDL.Nat], []),
  'processCopySale' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Principal, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'processSecondaryTrade' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Principal, IDL.Principal, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'processWalletCopySale' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Float64],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'processWalletMint' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'processWalletSecondaryTrade' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Principal, IDL.Float64],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'recordPurchase' : IDL.Func(
      [IDL.Text, IDL.Float64],
      [IDL.Variant({ 'ok' : PurchaseRecord, 'err' : IDL.Text })],
      [],
    ),
  'recordVideoHash' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchSetsByName' : IDL.Func([IDL.Text], [IDL.Vec(TcgSet)], ['query']),
  'setBtcRate' : IDL.Func([IDL.Float64], [], []),
  'toggleCardActive' : IDL.Func([IDL.Nat], [], []),
  'toggleCardSupported' : IDL.Func([IDL.Nat], [], []),
  'toggleCategoryActive' : IDL.Func([IDL.Nat], [], []),
  'toggleSetActive' : IDL.Func([IDL.Nat], [], []),
  'updateCard' : IDL.Func([UpdateTcgCardInput], [TcgCard], []),
  'updateCategory' : IDL.Func([UpdateTcgCategoryInput], [TcgCategory], []),
  'updateSet' : IDL.Func([UpdateTcgSetInput], [TcgSet], []),
  'uploadPreviewBlob' : IDL.Func([IDL.Vec(IDL.Nat8), IDL.Text], [IDL.Text], []),
  'uploadVideoBlob' : IDL.Func([IDL.Vec(IDL.Nat8), IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Track = IDL.Record({ 'title' : IDL.Text, 'duration' : IDL.Nat });
  const Album = IDL.Record({
    'id' : IDL.Text,
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'tracklist' : IDL.Vec(Track),
    'totalSupply' : IDL.Nat,
    'artist' : IDL.Text,
    'collectionName' : IDL.Text,
  });
  const AddPackInput = IDL.Record({
    'id' : IDL.Text,
    'coverImageUrl' : IDL.Text,
    'setName' : IDL.Text,
    'ownerPrincipal' : IDL.Principal,
    'totalSupply' : IDL.Nat,
    'releaseId' : IDL.Text,
    'serialNumber' : IDL.Nat,
    'packCount' : IDL.Nat,
  });
  const Release = IDL.Record({
    'album' : Album,
    'floorPrice' : IDL.Nat,
    'isActive' : IDL.Bool,
    'lastSoldPrice' : IDL.Nat,
    'mintedCount' : IDL.Nat,
    'ownersCount' : IDL.Nat,
    'mintOpenTime' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateTcgCardInput = IDL.Record({
    'cardName' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'isActive' : IDL.Bool,
    'setId' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'rarity' : IDL.Text,
    'cardNumber' : IDL.Text,
    'isSupported' : IDL.Bool,
  });
  const TcgCard = IDL.Record({
    'id' : IDL.Nat,
    'cardName' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'isActive' : IDL.Bool,
    'setId' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'rarity' : IDL.Text,
    'cardNumber' : IDL.Text,
    'isSupported' : IDL.Bool,
  });
  const CreateTcgCategoryInput = IDL.Record({
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
  });
  const TcgCategory = IDL.Record({
    'id' : IDL.Nat,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
  });
  const CreateTcgSetInput = IDL.Record({
    'setCode' : IDL.Text,
    'coverImageUrl' : IDL.Text,
    'setName' : IDL.Text,
    'featured' : IDL.Bool,
    'tcgCategory' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'slug' : IDL.Text,
    'isActive' : IDL.Bool,
    'cardCount' : IDL.Opt(IDL.Nat),
    'releaseYear' : IDL.Nat,
  });
  const TcgSet = IDL.Record({
    'id' : IDL.Nat,
    'setCode' : IDL.Text,
    'coverImageUrl' : IDL.Text,
    'setName' : IDL.Text,
    'featured' : IDL.Bool,
    'tcgCategory' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'slug' : IDL.Text,
    'isActive' : IDL.Bool,
    'cardCount' : IDL.Opt(IDL.Nat),
    'releaseYear' : IDL.Nat,
  });
  const WalletActivityType = IDL.Variant({
    'mintCost' : IDL.Null,
    'deposit' : IDL.Null,
    'auctionPayout' : IDL.Null,
  });
  const WalletActivity = IDL.Record({
    'status' : IDL.Variant({ 'pending' : IDL.Null, 'confirmed' : IDL.Null }),
    'activityType' : WalletActivityType,
    'btcAmountE8s' : IDL.Nat,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const BondingCurveState = IDL.Record({
    'startingPrice' : IDL.Float64,
    'clipId' : IDL.Text,
    'currentPrice' : IDL.Float64,
    'totalSupply' : IDL.Nat,
    'nextPrice' : IDL.Float64,
    'soldOut' : IDL.Bool,
    'priceIncrementFactor' : IDL.Float64,
    'copiesMinted' : IDL.Nat,
  });
  const CollectibleMediaType = IDL.Variant({
    'video' : IDL.Null,
    'photo' : IDL.Null,
  });
  const Collectible = IDL.Record({
    'id' : IDL.Text,
    'setName' : IDL.Text,
    'title' : IDL.Text,
    'creator' : IDL.Text,
    'typeSupply' : IDL.Nat,
    'editionNumber' : IDL.Nat,
    'ownerPrincipal' : IDL.Principal,
    'mintDate' : IDL.Text,
    'totalSupply' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'releaseId' : IDL.Text,
    'mediaType' : CollectibleMediaType,
    'rarity' : IDL.Text,
    'packId' : IDL.Text,
    'openedAt' : IDL.Int,
  });
  const PackStatus = IDL.Variant({ 'opened' : IDL.Null, 'sealed' : IDL.Null });
  const Pack = IDL.Record({
    'id' : IDL.Text,
    'status' : PackStatus,
    'coverImageUrl' : IDL.Text,
    'setName' : IDL.Text,
    'ownerPrincipal' : IDL.Principal,
    'createdAt' : IDL.Int,
    'totalSupply' : IDL.Nat,
    'releaseId' : IDL.Text,
    'serialNumber' : IDL.Nat,
    'packCount' : IDL.Nat,
    'collectibleId' : IDL.Opt(IDL.Text),
    'openedAt' : IDL.Opt(IDL.Int),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const VideoClipSort = IDL.Variant({
    'top' : IDL.Null,
    'trending' : IDL.Null,
    'newest' : IDL.Null,
  });
  const VideoClip = IDL.Record({
    'clip_id' : IDL.Text,
    'like_timestamps' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Int)),
    'title' : IDL.Opt(IDL.Text),
    'hashtags' : IDL.Vec(IDL.Text),
    'preview_loop_url' : IDL.Text,
    'like_count' : IDL.Nat,
    'likes_last_6_hours' : IDL.Nat,
    'likes_last_24_hours' : IDL.Nat,
    'timestamp' : IDL.Int,
    'likes_last_hour' : IDL.Nat,
    'explicit_flag' : IDL.Bool,
    'creator_principal_id' : IDL.Principal,
    'video_file_url' : IDL.Text,
  });
  const ListingStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'sold' : IDL.Null,
  });
  const Listing = IDL.Record({
    'id' : IDL.Nat,
    'status' : ListingStatus,
    'clipId' : IDL.Text,
    'totalEditions' : IDL.Nat,
    'sellerPrincipal' : IDL.Principal,
    'listPriceUsd' : IDL.Float64,
    'editionNumber' : IDL.Nat,
    'listedAt' : IDL.Int,
  });
  const MarketCapEntry = IDL.Record({
    'clipId' : IDL.Text,
    'title' : IDL.Text,
    'previewUrl' : IDL.Text,
    'totalSupply' : IDL.Nat,
    'creatorName' : IDL.Text,
    'currentPriceUsd' : IDL.Float64,
    'copiesSold' : IDL.Nat,
    'videoUrl' : IDL.Text,
    'marketCapUsd' : IDL.Float64,
  });
  const MarketListing = IDL.Record({
    'seller' : IDL.Principal,
    'editionId' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const EarningsSummary = IDL.Record({
    'totalBtcE8s' : IDL.Nat,
    'fromAuctionWins' : IDL.Float64,
    'fromCopySales' : IDL.Float64,
    'totalUsd' : IDL.Float64,
    'fromTradeRoyalties' : IDL.Float64,
    'transactionCount' : IDL.Nat,
  });
  const PurchaseStatus = IDL.Variant({
    'pending' : IDL.Null,
    'minted' : IDL.Null,
  });
  const PurchaseRecord = IDL.Record({
    'status' : PurchaseStatus,
    'clipId' : IDL.Text,
    'editionNumber' : IDL.Nat,
    'purchasedAt' : IDL.Int,
    'buyerPrincipal' : IDL.Principal,
    'pricePaid' : IDL.Float64,
    'purchaseId' : IDL.Text,
  });
  const TxType = IDL.Variant({
    'mintFee' : IDL.Null,
    'secondaryTrade' : IDL.Null,
    'copySale' : IDL.Null,
  });
  const TxSplit = IDL.Record({
    'principal' : IDL.Principal,
    'role' : IDL.Text,
    'usdAmount' : IDL.Float64,
    'btcAmountSimulated' : IDL.Float64,
    'btcAddress' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'clipId' : IDL.Text,
    'totalUsd' : IDL.Float64,
    'timestamp' : IDL.Int,
    'txType' : TxType,
    'splits' : IDL.Vec(TxSplit),
  });
  const OfferStatus = IDL.Variant({
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  });
  const Offer = IDL.Record({
    'id' : IDL.Nat,
    'status' : OfferStatus,
    'offerPriceUsd' : IDL.Float64,
    'listingId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'buyerPrincipal' : IDL.Principal,
  });
  const ConfirmationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Deposit = IDL.Record({
    'depositId' : IDL.Text,
    'confirmationStatus' : ConfirmationStatus,
    'btcAmountE8s' : IDL.Nat,
    'txid' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const PayoutType = IDL.Variant({
    'auctionWin' : IDL.Null,
    'copySale' : IDL.Null,
    'secondaryRoyalty' : IDL.Null,
  });
  const Payout = IDL.Record({
    'clipId' : IDL.Text,
    'btcAmountE8s' : IDL.Nat,
    'payoutId' : IDL.Text,
    'timestamp' : IDL.Int,
    'payoutType' : PayoutType,
  });
  const UserWallet = IDL.Record({
    'walletPrincipalId' : IDL.Principal,
    'usdValueRef' : IDL.Float64,
    'btcAddress' : IDL.Text,
    'deposits' : IDL.Vec(Deposit),
    'payouts' : IDL.Vec(Payout),
    'btcBalanceE8s' : IDL.Nat,
  });
  const PricePoint = IDL.Record({
    'editionNumber' : IDL.Nat,
    'timestamp' : IDL.Int,
    'salePrice' : IDL.Float64,
  });
  const PriceHistorySummary = IDL.Record({
    'currentPrice' : IDL.Float64,
    'maxPrice' : IDL.Float64,
    'totalSales' : IDL.Nat,
    'minPrice' : IDL.Float64,
    'lastSaleTimestamp' : IDL.Opt(IDL.Int),
    'firstSaleTimestamp' : IDL.Opt(IDL.Int),
  });
  const VideoAsset = IDL.Record({
    'owner' : IDL.Principal,
    'data' : IDL.Vec(IDL.Nat8),
    'content_type' : IDL.Text,
    'created_at' : IDL.Int,
    'asset_id' : IDL.Text,
  });
  const PackOpenResult = IDL.Variant({ 'ok' : Collectible, 'err' : IDL.Text });
  const UpdateTcgCardInput = IDL.Record({
    'id' : IDL.Nat,
    'cardName' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'isActive' : IDL.Bool,
    'setId' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'rarity' : IDL.Text,
    'cardNumber' : IDL.Text,
    'isSupported' : IDL.Bool,
  });
  const UpdateTcgCategoryInput = IDL.Record({
    'id' : IDL.Nat,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
  });
  const UpdateTcgSetInput = IDL.Record({
    'id' : IDL.Nat,
    'setCode' : IDL.Text,
    'coverImageUrl' : IDL.Text,
    'setName' : IDL.Text,
    'featured' : IDL.Bool,
    'tcgCategory' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'slug' : IDL.Text,
    'isActive' : IDL.Bool,
    'cardCount' : IDL.Opt(IDL.Nat),
    'releaseYear' : IDL.Nat,
  });
  
  return IDL.Service({
    'acceptOffer' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'addAlbum' : IDL.Func([Album], [], []),
    'addPack' : IDL.Func([AddPackInput], [], []),
    'addRelease' : IDL.Func([Release], [], []),
    'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelListing' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'checkForNewDeposits' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'checkLikeRateLimit' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'checkMintRateLimit' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'confirmPendingDeposits' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'createCard' : IDL.Func([CreateTcgCardInput], [TcgCard], []),
    'createCategory' : IDL.Func([CreateTcgCategoryInput], [TcgCategory], []),
    'createClip' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Vec(IDL.Text), IDL.Bool],
        [IDL.Text],
        [],
      ),
    'createListing' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Float64],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'createSet' : IDL.Func([CreateTcgSetInput], [TcgSet], []),
    'declineOffer' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteCard' : IDL.Func([IDL.Nat], [], []),
    'deleteCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteSet' : IDL.Func([IDL.Nat], [], []),
    'getAlbumById' : IDL.Func([IDL.Text], [IDL.Opt(Album)], ['query']),
    'getAlbums' : IDL.Func([], [IDL.Vec(Album)], ['query']),
    'getAllCardsAdmin' : IDL.Func([], [IDL.Vec(TcgCard)], ['query']),
    'getAllCategoriesAdmin' : IDL.Func([], [IDL.Vec(TcgCategory)], ['query']),
    'getAllSetsAdmin' : IDL.Func([], [IDL.Vec(TcgSet)], ['query']),
    'getAllWalletActivity' : IDL.Func([], [IDL.Vec(WalletActivity)], []),
    'getBondingCurveState' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(BondingCurveState)],
        ['query'],
      ),
    'getBondingCurveStates' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(BondingCurveState)],
        ['query'],
      ),
    'getBtcRate' : IDL.Func([], [IDL.Float64], ['query']),
    'getCallerCollectibles' : IDL.Func([], [IDL.Vec(Collectible)], ['query']),
    'getCallerPacks' : IDL.Func([], [IDL.Vec(Pack)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCardsBySet' : IDL.Func([IDL.Nat], [IDL.Vec(TcgCard)], ['query']),
    'getCardsBySetAdmin' : IDL.Func([IDL.Nat], [IDL.Vec(TcgCard)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(TcgCategory)], ['query']),
    'getClips' : IDL.Func(
        [VideoClipSort, IDL.Bool],
        [IDL.Vec(VideoClip)],
        ['query'],
      ),
    'getClipsByHashtag' : IDL.Func([IDL.Text], [IDL.Vec(VideoClip)], ['query']),
    'getClipsForHashtag' : IDL.Func(
        [IDL.Text, VideoClipSort, IDL.Bool],
        [IDL.Vec(VideoClip)],
        ['query'],
      ),
    'getClipsWithCurveState' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(VideoClip, IDL.Opt(BondingCurveState)))],
        ['query'],
      ),
    'getCreatorClips' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(VideoClip)],
        ['query'],
      ),
    'getCurrentPrice' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getFeaturedSets' : IDL.Func([], [IDL.Vec(TcgSet)], ['query']),
    'getListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getListingsByClip' : IDL.Func([IDL.Text], [IDL.Vec(Listing)], ['query']),
    'getMarketCap' : IDL.Func([IDL.Text], [IDL.Opt(MarketCapEntry)], ['query']),
    'getMarketListings' : IDL.Func([], [IDL.Vec(MarketListing)], ['query']),
    'getMyBalance' : IDL.Func([], [IDL.Nat], []),
    'getMyEarnings' : IDL.Func([], [EarningsSummary], ['query']),
    'getMyPurchases' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
    'getMyRole' : IDL.Func([], [UserRole], ['query']),
    'getMyTransactions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getOfferHistory' : IDL.Func([IDL.Nat], [IDL.Vec(Offer)], ['query']),
    'getOffers' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Vec(Offer), 'err' : IDL.Text })],
        ['query'],
      ),
    'getOrCreateUserWallet' : IDL.Func([], [UserWallet], []),
    'getPaymentAddress' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getPokemonSets' : IDL.Func([], [IDL.Vec(TcgSet)], ['query']),
    'getPriceHistory' : IDL.Func([IDL.Text], [IDL.Vec(PricePoint)], ['query']),
    'getPriceHistoryFull' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PricePoint)],
        ['query'],
      ),
    'getPriceHistorySummary' : IDL.Func(
        [IDL.Text],
        [PriceHistorySummary],
        ['query'],
      ),
    'getReleases' : IDL.Func([], [IDL.Vec(Release)], ['query']),
    'getSetById' : IDL.Func([IDL.Nat], [IDL.Opt(TcgSet)], ['query']),
    'getSetBySlug' : IDL.Func([IDL.Text], [IDL.Opt(TcgSet)], ['query']),
    'getSets' : IDL.Func([], [IDL.Vec(TcgSet)], ['query']),
    'getSetsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(TcgSet)], ['query']),
    'getTop10ByMarketCap' : IDL.Func([], [IDL.Vec(MarketCapEntry)], ['query']),
    'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getTrendingHashtags' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getTrendingHashtagsWithHotFlag' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Bool))],
        ['query'],
      ),
    'getUserCollectibles' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Collectible)],
        ['query'],
      ),
    'getUserDepositAddress' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getUserDeposits' : IDL.Func([], [IDL.Vec(Deposit)], []),
    'getUserPacks' : IDL.Func([IDL.Principal], [IDL.Vec(Pack)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideoBlob' : IDL.Func([IDL.Text], [IDL.Opt(VideoAsset)], ['query']),
    'initBondingCurve' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : BondingCurveState, 'err' : IDL.Text })],
        [],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeClip' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'makeOffer' : IDL.Func(
        [IDL.Nat, IDL.Float64],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'openPack' : IDL.Func([IDL.Text], [PackOpenResult], []),
    'processClipMint' : IDL.Func([IDL.Principal], [IDL.Nat], []),
    'processCopySale' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Principal, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'processSecondaryTrade' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Principal, IDL.Principal, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'processWalletCopySale' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Float64],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'processWalletMint' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'processWalletSecondaryTrade' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Principal, IDL.Float64],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'recordPurchase' : IDL.Func(
        [IDL.Text, IDL.Float64],
        [IDL.Variant({ 'ok' : PurchaseRecord, 'err' : IDL.Text })],
        [],
      ),
    'recordVideoHash' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchSetsByName' : IDL.Func([IDL.Text], [IDL.Vec(TcgSet)], ['query']),
    'setBtcRate' : IDL.Func([IDL.Float64], [], []),
    'toggleCardActive' : IDL.Func([IDL.Nat], [], []),
    'toggleCardSupported' : IDL.Func([IDL.Nat], [], []),
    'toggleCategoryActive' : IDL.Func([IDL.Nat], [], []),
    'toggleSetActive' : IDL.Func([IDL.Nat], [], []),
    'updateCard' : IDL.Func([UpdateTcgCardInput], [TcgCard], []),
    'updateCategory' : IDL.Func([UpdateTcgCategoryInput], [TcgCategory], []),
    'updateSet' : IDL.Func([UpdateTcgSetInput], [TcgSet], []),
    'uploadPreviewBlob' : IDL.Func(
        [IDL.Vec(IDL.Nat8), IDL.Text],
        [IDL.Text],
        [],
      ),
    'uploadVideoBlob' : IDL.Func([IDL.Vec(IDL.Nat8), IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };