/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Track = IDL.Record({ 'title' : IDL.Text, 'duration' : IDL.Nat });
export const Album = IDL.Record({
  'id' : IDL.Text,
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'tracklist' : IDL.Vec(Track),
  'totalSupply' : IDL.Nat,
  'artist' : IDL.Text,
  'collectionName' : IDL.Text,
});
export const Release = IDL.Record({
  'album' : Album,
  'floorPrice' : IDL.Nat,
  'isActive' : IDL.Bool,
  'lastSoldPrice' : IDL.Nat,
  'mintedCount' : IDL.Nat,
  'ownersCount' : IDL.Nat,
  'mintOpenTime' : IDL.Int,
});
export const MarketListing = IDL.Record({
  'seller' : IDL.Principal,
  'editionId' : IDL.Nat,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addAlbum' : IDL.Func([Album], [], []),
  'addRelease' : IDL.Func([Release], [], []),
  'getAlbumById' : IDL.Func([IDL.Text], [IDL.Opt(Album)], ['query']),
  'getAlbums' : IDL.Func([], [IDL.Vec(Album)], ['query']),
  'getMarketListings' : IDL.Func([], [IDL.Vec(MarketListing)], ['query']),
  'getReleases' : IDL.Func([], [IDL.Vec(Release)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Track = IDL.Record({ 'title' : IDL.Text, 'duration' : IDL.Nat });
  const Album = IDL.Record({
    'id' : IDL.Text,
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'tracklist' : IDL.Vec(Track),
    'totalSupply' : IDL.Nat,
    'artist' : IDL.Text,
    'collectionName' : IDL.Text,
  });
  const Release = IDL.Record({
    'album' : Album,
    'floorPrice' : IDL.Nat,
    'isActive' : IDL.Bool,
    'lastSoldPrice' : IDL.Nat,
    'mintedCount' : IDL.Nat,
    'ownersCount' : IDL.Nat,
    'mintOpenTime' : IDL.Int,
  });
  const MarketListing = IDL.Record({
    'seller' : IDL.Principal,
    'editionId' : IDL.Nat,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addAlbum' : IDL.Func([Album], [], []),
    'addRelease' : IDL.Func([Release], [], []),
    'getAlbumById' : IDL.Func([IDL.Text], [IDL.Opt(Album)], ['query']),
    'getAlbums' : IDL.Func([], [IDL.Vec(Album)], ['query']),
    'getMarketListings' : IDL.Func([], [IDL.Vec(MarketListing)], ['query']),
    'getReleases' : IDL.Func([], [IDL.Vec(Release)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };