/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddPackInput {
  'id' : string,
  'coverImageUrl' : string,
  'setName' : string,
  'ownerPrincipal' : Principal,
  'totalSupply' : bigint,
  'releaseId' : string,
  'serialNumber' : bigint,
  'packCount' : bigint,
}
export interface Album {
  'id' : string,
  'coverImageUrl' : string,
  'title' : string,
  'tracklist' : Array<Track>,
  'totalSupply' : bigint,
  'artist' : string,
  'collectionName' : string,
}
export interface Collectible {
  'id' : string,
  'setName' : string,
  'title' : string,
  'creator' : string,
  'typeSupply' : bigint,
  'editionNumber' : bigint,
  'ownerPrincipal' : Principal,
  'mintDate' : string,
  'totalSupply' : bigint,
  'imageUrl' : string,
  'releaseId' : string,
  'mediaType' : CollectibleMediaType,
  'rarity' : string,
  'packId' : string,
  'openedAt' : bigint,
}
export type CollectibleMediaType = { 'video' : null } |
  { 'photo' : null };
export interface CreateTcgCardInput {
  'cardName' : string,
  'sortOrder' : bigint,
  'isActive' : boolean,
  'setId' : bigint,
  'imageUrl' : string,
  'rarity' : string,
  'cardNumber' : string,
  'isSupported' : boolean,
}
export interface CreateTcgCategoryInput {
  'sortOrder' : bigint,
  'name' : string,
  'slug' : string,
  'isActive' : boolean,
  'imageUrl' : string,
}
export interface CreateTcgSetInput {
  'setCode' : string,
  'coverImageUrl' : string,
  'setName' : string,
  'featured' : boolean,
  'tcgCategory' : string,
  'sortOrder' : bigint,
  'slug' : string,
  'isActive' : boolean,
  'cardCount' : [] | [bigint],
  'releaseYear' : bigint,
}
export type LikeResult = { 'ok' : bigint } |
  { 'alreadyLiked' : null } |
  { 'notFound' : null };
export interface MarketListing {
  'seller' : Principal,
  'editionId' : bigint,
  'price' : bigint,
}
export interface Pack {
  'id' : string,
  'status' : PackStatus,
  'coverImageUrl' : string,
  'setName' : string,
  'ownerPrincipal' : Principal,
  'createdAt' : bigint,
  'totalSupply' : bigint,
  'releaseId' : string,
  'serialNumber' : bigint,
  'packCount' : bigint,
  'collectibleId' : [] | [string],
  'openedAt' : [] | [bigint],
}
export type PackOpenResult = { 'ok' : Collectible } |
  { 'err' : string };
export type PackStatus = { 'opened' : null } |
  { 'sealed' : null };
export interface Release {
  'album' : Album,
  'floorPrice' : bigint,
  'isActive' : boolean,
  'lastSoldPrice' : bigint,
  'mintedCount' : bigint,
  'ownersCount' : bigint,
  'mintOpenTime' : bigint,
}
export interface TcgCard {
  'id' : bigint,
  'cardName' : string,
  'sortOrder' : bigint,
  'isActive' : boolean,
  'setId' : bigint,
  'imageUrl' : string,
  'rarity' : string,
  'cardNumber' : string,
  'isSupported' : boolean,
}
export interface TcgCategory {
  'id' : bigint,
  'sortOrder' : bigint,
  'name' : string,
  'slug' : string,
  'isActive' : boolean,
  'imageUrl' : string,
}
export interface TcgSet {
  'id' : bigint,
  'setCode' : string,
  'coverImageUrl' : string,
  'setName' : string,
  'featured' : boolean,
  'tcgCategory' : string,
  'sortOrder' : bigint,
  'slug' : string,
  'isActive' : boolean,
  'cardCount' : [] | [bigint],
  'releaseYear' : bigint,
}
export interface Track { 'title' : string, 'duration' : bigint }
export interface UpdateTcgCardInput {
  'id' : bigint,
  'cardName' : string,
  'sortOrder' : bigint,
  'isActive' : boolean,
  'setId' : bigint,
  'imageUrl' : string,
  'rarity' : string,
  'cardNumber' : string,
  'isSupported' : boolean,
}
export interface UpdateTcgCategoryInput {
  'id' : bigint,
  'sortOrder' : bigint,
  'name' : string,
  'slug' : string,
  'isActive' : boolean,
  'imageUrl' : string,
}
export interface UpdateTcgSetInput {
  'id' : bigint,
  'setCode' : string,
  'coverImageUrl' : string,
  'setName' : string,
  'featured' : boolean,
  'tcgCategory' : string,
  'sortOrder' : bigint,
  'slug' : string,
  'isActive' : boolean,
  'cardCount' : [] | [bigint],
  'releaseYear' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoClip {
  'clip_id' : string,
  'like_timestamps' : Array<[Principal, bigint]>,
  'title' : [] | [string],
  'hashtags' : Array<string>,
  'preview_loop_url' : string,
  'like_count' : bigint,
  'likes_last_6_hours' : bigint,
  'likes_last_24_hours' : bigint,
  'timestamp' : bigint,
  'likes_last_hour' : bigint,
  'explicit_flag' : boolean,
  'creator_principal_id' : Principal,
  'video_file_url' : string,
}
export type VideoClipSort = { 'top' : null } |
  { 'trending' : null } |
  { 'newest' : null };
export interface _SERVICE {
  'addAlbum' : ActorMethod<[Album], undefined>,
  'addPack' : ActorMethod<[AddPackInput], undefined>,
  'addRelease' : ActorMethod<[Release], undefined>,
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCard' : ActorMethod<[CreateTcgCardInput], TcgCard>,
  'createCategory' : ActorMethod<[CreateTcgCategoryInput], TcgCategory>,
  /**
   * / Create a new video clip post. Returns the generated clip_id.
   */
  'createClip' : ActorMethod<
    [string, string, [] | [string], Array<string>, boolean],
    string
  >,
  'createSet' : ActorMethod<[CreateTcgSetInput], TcgSet>,
  'deleteCard' : ActorMethod<[bigint], undefined>,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteSet' : ActorMethod<[bigint], undefined>,
  'getAlbumById' : ActorMethod<[string], [] | [Album]>,
  'getAlbums' : ActorMethod<[], Array<Album>>,
  'getAllCardsAdmin' : ActorMethod<[], Array<TcgCard>>,
  'getAllCategoriesAdmin' : ActorMethod<[], Array<TcgCategory>>,
  'getAllSetsAdmin' : ActorMethod<[], Array<TcgSet>>,
  'getCallerCollectibles' : ActorMethod<[], Array<Collectible>>,
  'getCallerPacks' : ActorMethod<[], Array<Pack>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCardsBySet' : ActorMethod<[bigint], Array<TcgCard>>,
  'getCardsBySetAdmin' : ActorMethod<[bigint], Array<TcgCard>>,
  'getCategories' : ActorMethod<[], Array<TcgCategory>>,
  /**
   * / Fetch clips sorted by newest, trending (viral score), or top (total likes).
   * / safeView=true hides explicit clips.
   */
  'getClips' : ActorMethod<[VideoClipSort, boolean], Array<VideoClip>>,
  /**
   * / Fetch clips filtered to a specific hashtag.
   */
  'getClipsByHashtag' : ActorMethod<[string], Array<VideoClip>>,
  /**
   * / Get all clips created by a specific principal.
   */
  'getCreatorClips' : ActorMethod<[Principal], Array<VideoClip>>,
  'getFeaturedSets' : ActorMethod<[], Array<TcgSet>>,
  'getMarketListings' : ActorMethod<[], Array<MarketListing>>,
  'getMyRole' : ActorMethod<[], UserRole>,
  'getPokemonSets' : ActorMethod<[], Array<TcgSet>>,
  'getReleases' : ActorMethod<[], Array<Release>>,
  'getSetById' : ActorMethod<[bigint], [] | [TcgSet]>,
  'getSetBySlug' : ActorMethod<[string], [] | [TcgSet]>,
  'getSets' : ActorMethod<[], Array<TcgSet>>,
  'getSetsByCategory' : ActorMethod<[string], Array<TcgSet>>,
  /**
   * / Get trending hashtags with their post counts, sorted by count descending.
   */
  'getTrendingHashtags' : ActorMethod<[], Array<[string, bigint]>>,
  'getUserCollectibles' : ActorMethod<[Principal], Array<Collectible>>,
  'getUserPacks' : ActorMethod<[Principal], Array<Pack>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[], boolean>,
  /**
   * / Like a clip. Each caller can only like once. Returns new like_count.
   */
  'likeClip' : ActorMethod<[string], LikeResult>,
  'openPack' : ActorMethod<[string], PackOpenResult>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchSetsByName' : ActorMethod<[string], Array<TcgSet>>,
  'toggleCardActive' : ActorMethod<[bigint], undefined>,
  'toggleCardSupported' : ActorMethod<[bigint], undefined>,
  'toggleCategoryActive' : ActorMethod<[bigint], undefined>,
  'toggleSetActive' : ActorMethod<[bigint], undefined>,
  'updateCard' : ActorMethod<[UpdateTcgCardInput], TcgCard>,
  'updateCategory' : ActorMethod<[UpdateTcgCategoryInput], TcgCategory>,
  'updateSet' : ActorMethod<[UpdateTcgSetInput], TcgSet>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];