/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddPackInput {
  'id' : string,
  'coverImageUrl' : string,
  'setName' : string,
  'ownerPrincipal' : Principal,
  'totalSupply' : bigint,
  'releaseId' : string,
  'serialNumber' : bigint,
  'packCount' : bigint,
}
export interface Album {
  'id' : string,
  'coverImageUrl' : string,
  'title' : string,
  'tracklist' : Array<Track>,
  'totalSupply' : bigint,
  'artist' : string,
  'collectionName' : string,
}
export interface BondingCurveState {
  'startingPrice' : number,
  'clipId' : string,
  'currentPrice' : number,
  'totalSupply' : bigint,
  'nextPrice' : number,
  'soldOut' : boolean,
  'priceIncrementFactor' : number,
  'copiesMinted' : bigint,
}
export interface Collectible {
  'id' : string,
  'setName' : string,
  'title' : string,
  'creator' : string,
  'typeSupply' : bigint,
  'editionNumber' : bigint,
  'ownerPrincipal' : Principal,
  'mintDate' : string,
  'totalSupply' : bigint,
  'imageUrl' : string,
  'releaseId' : string,
  'mediaType' : CollectibleMediaType,
  'rarity' : string,
  'packId' : string,
  'openedAt' : bigint,
}
export type CollectibleMediaType = { 'video' : null } |
  { 'photo' : null };
export type ConfirmationStatus = { 'pending' : null } |
  { 'confirmed' : null };
export interface CreateTcgCardInput {
  'cardName' : string,
  'sortOrder' : bigint,
  'isActive' : boolean,
  'setId' : bigint,
  'imageUrl' : string,
  'rarity' : string,
  'cardNumber' : string,
  'isSupported' : boolean,
}
export interface CreateTcgCategoryInput {
  'sortOrder' : bigint,
  'name' : string,
  'slug' : string,
  'isActive' : boolean,
  'imageUrl' : string,
}
export interface CreateTcgSetInput {
  'setCode' : string,
  'coverImageUrl' : string,
  'setName' : string,
  'featured' : boolean,
  'tcgCategory' : string,
  'sortOrder' : bigint,
  'slug' : string,
  'isActive' : boolean,
  'cardCount' : [] | [bigint],
  'releaseYear' : bigint,
}
export interface Deposit {
  'depositId' : string,
  'confirmationStatus' : ConfirmationStatus,
  'btcAmountE8s' : bigint,
  'txid' : string,
  'timestamp' : bigint,
}
export interface EarningsSummary {
  'totalBtcE8s' : bigint,
  'fromAuctionWins' : number,
  'fromCopySales' : number,
  'totalUsd' : number,
  'fromTradeRoyalties' : number,
  'transactionCount' : bigint,
}
export interface Listing {
  'id' : bigint,
  'status' : ListingStatus,
  'clipId' : string,
  'totalEditions' : bigint,
  'sellerPrincipal' : Principal,
  'listPriceUsd' : number,
  'editionNumber' : bigint,
  'listedAt' : bigint,
}
export type ListingStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'sold' : null };
export interface MarketCapEntry {
  'clipId' : string,
  'title' : string,
  'previewUrl' : string,
  'totalSupply' : bigint,
  'creatorName' : string,
  'currentPriceUsd' : number,
  'copiesSold' : bigint,
  'videoUrl' : string,
  'marketCapUsd' : number,
}
export interface MarketListing {
  'seller' : Principal,
  'editionId' : bigint,
  'price' : bigint,
}
export interface Offer {
  'id' : bigint,
  'status' : OfferStatus,
  'offerPriceUsd' : number,
  'listingId' : bigint,
  'createdAt' : bigint,
  'buyerPrincipal' : Principal,
}
export type OfferStatus = { 'pending' : null } |
  { 'accepted' : null } |
  { 'declined' : null };
export interface Pack {
  'id' : string,
  'status' : PackStatus,
  'coverImageUrl' : string,
  'setName' : string,
  'ownerPrincipal' : Principal,
  'createdAt' : bigint,
  'totalSupply' : bigint,
  'releaseId' : string,
  'serialNumber' : bigint,
  'packCount' : bigint,
  'collectibleId' : [] | [string],
  'openedAt' : [] | [bigint],
}
export type PackOpenResult = { 'ok' : Collectible } |
  { 'err' : string };
export type PackStatus = { 'opened' : null } |
  { 'sealed' : null };
export interface Payout {
  'clipId' : string,
  'btcAmountE8s' : bigint,
  'payoutId' : string,
  'timestamp' : bigint,
  'payoutType' : PayoutType,
}
export type PayoutType = { 'auctionWin' : null } |
  { 'copySale' : null } |
  { 'secondaryRoyalty' : null };
export interface PriceHistorySummary {
  'currentPrice' : number,
  'maxPrice' : number,
  'totalSales' : bigint,
  'minPrice' : number,
  'lastSaleTimestamp' : [] | [bigint],
  'firstSaleTimestamp' : [] | [bigint],
}
export interface PricePoint {
  'editionNumber' : bigint,
  'timestamp' : bigint,
  'salePrice' : number,
}
export interface PurchaseRecord {
  'status' : PurchaseStatus,
  'clipId' : string,
  'editionNumber' : bigint,
  'purchasedAt' : bigint,
  'buyerPrincipal' : Principal,
  'pricePaid' : number,
  'purchaseId' : string,
}
export type PurchaseStatus = { 'pending' : null } |
  { 'minted' : null };
export interface Release {
  'album' : Album,
  'floorPrice' : bigint,
  'isActive' : boolean,
  'lastSoldPrice' : bigint,
  'mintedCount' : bigint,
  'ownersCount' : bigint,
  'mintOpenTime' : bigint,
}
export interface TcgCard {
  'id' : bigint,
  'cardName' : string,
  'sortOrder' : bigint,
  'isActive' : boolean,
  'setId' : bigint,
  'imageUrl' : string,
  'rarity' : string,
  'cardNumber' : string,
  'isSupported' : boolean,
}
export interface TcgCategory {
  'id' : bigint,
  'sortOrder' : bigint,
  'name' : string,
  'slug' : string,
  'isActive' : boolean,
  'imageUrl' : string,
}
export interface TcgSet {
  'id' : bigint,
  'setCode' : string,
  'coverImageUrl' : string,
  'setName' : string,
  'featured' : boolean,
  'tcgCategory' : string,
  'sortOrder' : bigint,
  'slug' : string,
  'isActive' : boolean,
  'cardCount' : [] | [bigint],
  'releaseYear' : bigint,
}
export interface Track { 'title' : string, 'duration' : bigint }
export interface Transaction {
  'id' : bigint,
  'status' : string,
  'clipId' : string,
  'totalUsd' : number,
  'timestamp' : bigint,
  'txType' : TxType,
  'splits' : Array<TxSplit>,
}
export interface TxSplit {
  'principal' : Principal,
  'role' : string,
  'usdAmount' : number,
  'btcAmountSimulated' : number,
  'btcAddress' : string,
}
export type TxType = { 'mintFee' : null } |
  { 'secondaryTrade' : null } |
  { 'copySale' : null };
export interface UpdateTcgCardInput {
  'id' : bigint,
  'cardName' : string,
  'sortOrder' : bigint,
  'isActive' : boolean,
  'setId' : bigint,
  'imageUrl' : string,
  'rarity' : string,
  'cardNumber' : string,
  'isSupported' : boolean,
}
export interface UpdateTcgCategoryInput {
  'id' : bigint,
  'sortOrder' : bigint,
  'name' : string,
  'slug' : string,
  'isActive' : boolean,
  'imageUrl' : string,
}
export interface UpdateTcgSetInput {
  'id' : bigint,
  'setCode' : string,
  'coverImageUrl' : string,
  'setName' : string,
  'featured' : boolean,
  'tcgCategory' : string,
  'sortOrder' : bigint,
  'slug' : string,
  'isActive' : boolean,
  'cardCount' : [] | [bigint],
  'releaseYear' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserWallet {
  'walletPrincipalId' : Principal,
  'usdValueRef' : number,
  'btcAddress' : string,
  'deposits' : Array<Deposit>,
  'payouts' : Array<Payout>,
  'btcBalanceE8s' : bigint,
}
export interface VideoAsset {
  'owner' : Principal,
  'data' : Uint8Array,
  'content_type' : string,
  'created_at' : bigint,
  'asset_id' : string,
}
export interface VideoClip {
  'clip_id' : string,
  'like_timestamps' : Array<[Principal, bigint]>,
  'title' : [] | [string],
  'hashtags' : Array<string>,
  'preview_loop_url' : string,
  'like_count' : bigint,
  'likes_last_6_hours' : bigint,
  'likes_last_24_hours' : bigint,
  'timestamp' : bigint,
  'likes_last_hour' : bigint,
  'explicit_flag' : boolean,
  'creator_principal_id' : Principal,
  'video_file_url' : string,
}
export type VideoClipSort = { 'top' : null } |
  { 'trending' : null } |
  { 'newest' : null };
export interface WalletActivity {
  'status' : { 'pending' : null } |
    { 'confirmed' : null },
  'activityType' : WalletActivityType,
  'btcAmountE8s' : bigint,
  'description' : string,
  'timestamp' : bigint,
}
export type WalletActivityType = { 'mintCost' : null } |
  { 'deposit' : null } |
  { 'withdrawal' : null } |
  { 'auctionPayout' : null };
export interface _SERVICE {
  'acceptOffer' : ActorMethod<
    [bigint],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'addAlbum' : ActorMethod<[Album], undefined>,
  'addPack' : ActorMethod<[AddPackInput], undefined>,
  'addRelease' : ActorMethod<[Release], undefined>,
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelListing' : ActorMethod<
    [bigint],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  /**
   * / Check for new incoming UTXOs on the caller's BTC deposit address using ICP's Bitcoin API.
   * / Credits balance for UTXOs with height > 0 (at least 1 confirmation).
   * / Tracks seen UTXO outpoints to prevent double-crediting.
   */
  'checkForNewDeposits' : ActorMethod<
    [],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  /**
   * / Check whether the caller is allowed to like (max 30 likes per minute;
   * / also blocks accounts created within the last 60 seconds).
   * / Returns #ok(true) when allowed, #err with a human-readable message when blocked.
   */
  'checkLikeRateLimit' : ActorMethod<
    [],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  /**
   * / Check whether the caller is allowed to mint (max 10 mints per 10 minutes).
   * / Returns #ok(true) when allowed, #err with a human-readable message when blocked.
   */
  'checkMintRateLimit' : ActorMethod<
    [],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  /**
   * / Re-check pending deposits using the ICP Bitcoin API.
   * / Confirms deposits whose UTXO now has >= 1 confirmation and credits balance.
   */
  'confirmPendingDeposits' : ActorMethod<
    [],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'createCard' : ActorMethod<[CreateTcgCardInput], TcgCard>,
  'createCategory' : ActorMethod<[CreateTcgCategoryInput], TcgCategory>,
  /**
   * / Create a new video clip post. Returns the generated clip_id.
   */
  'createClip' : ActorMethod<
    [string, string, [] | [string], Array<string>, boolean],
    string
  >,
  /**
   * / Call the ckBTC minter canister to get the unique deposit address for the caller.
   * / The ckBTC minter returns a real Bitcoin address (bech32 bc1... or P2PKH 1...) for the user.
   * / Only call this when the wallet exists but btcAddress is empty.
   * / Retries up to 3 times on empty address (minter occasionally returns empty on first call).
   * / On success: stores the address permanently and returns {#ok: address}.
   * / On empty response after all retries or any error: returns {#err: real error message}.
   */
  'createDepositAddress' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createListing' : ActorMethod<
    [string, bigint, number],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'createSet' : ActorMethod<[CreateTcgSetInput], TcgSet>,
  'declineOffer' : ActorMethod<
    [bigint],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteCard' : ActorMethod<[bigint], undefined>,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteSet' : ActorMethod<[bigint], undefined>,
  'getAlbumById' : ActorMethod<[string], [] | [Album]>,
  'getAlbums' : ActorMethod<[], Array<Album>>,
  'getAllCardsAdmin' : ActorMethod<[], Array<TcgCard>>,
  'getAllCategoriesAdmin' : ActorMethod<[], Array<TcgCategory>>,
  'getAllSetsAdmin' : ActorMethod<[], Array<TcgSet>>,
  /**
   * / Returns merged wallet activity (deposits + payouts + mint costs) newest-first.
   */
  'getAllWalletActivity' : ActorMethod<[], Array<WalletActivity>>,
  /**
   * / Get the bonding curve state for a single clip.
   */
  'getBondingCurveState' : ActorMethod<[string], [] | [BondingCurveState]>,
  /**
   * / Batch-fetch bonding curve states for multiple clips (for feed rendering).
   */
  'getBondingCurveStates' : ActorMethod<
    [Array<string>],
    Array<BondingCurveState>
  >,
  /**
   * / Returns the current USD/BTC rate used for conversions.
   * / Defaults to 50000 if no live rate is set.
   */
  'getBtcRate' : ActorMethod<[], number>,
  'getCallerCollectibles' : ActorMethod<[], Array<Collectible>>,
  'getCallerPacks' : ActorMethod<[], Array<Pack>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCardsBySet' : ActorMethod<[bigint], Array<TcgCard>>,
  'getCardsBySetAdmin' : ActorMethod<[bigint], Array<TcgCard>>,
  'getCategories' : ActorMethod<[], Array<TcgCategory>>,
  /**
   * / Fetch clips sorted by newest, trending (viral score), or top (total likes).
   * / safeView=true hides explicit clips.
   */
  'getClips' : ActorMethod<[VideoClipSort, boolean], Array<VideoClip>>,
  /**
   * / Fetch clips filtered to a specific hashtag.
   * / Delegates to getClipsForHashtag with newest sort and no safe view filter.
   */
  'getClipsByHashtag' : ActorMethod<[string], Array<VideoClip>>,
  /**
   * / Fetch clips filtered to a specific hashtag (case-insensitive), then sorted.
   */
  'getClipsForHashtag' : ActorMethod<
    [string, VideoClipSort, boolean],
    Array<VideoClip>
  >,
  /**
   * / Get all clips together with their bonding curve state in one call.
   */
  'getClipsWithCurveState' : ActorMethod<
    [],
    Array<[VideoClip, [] | [BondingCurveState]]>
  >,
  /**
   * / Get all clips created by a specific principal.
   */
  'getCreatorClips' : ActorMethod<[Principal], Array<VideoClip>>,
  'getCurrentPrice' : ActorMethod<[string], number>,
  'getFeaturedSets' : ActorMethod<[], Array<TcgSet>>,
  'getListings' : ActorMethod<[], Array<Listing>>,
  'getListingsByClip' : ActorMethod<[string], Array<Listing>>,
  'getMarketCap' : ActorMethod<[string], [] | [MarketCapEntry]>,
  'getMarketListings' : ActorMethod<[], Array<MarketListing>>,
  /**
   * / Returns the caller's in-app BTC balance in e8s (from UserWallet).
   * / Displayed on the frontend as BTC (e8s / 100_000_000).
   */
  'getMyBalance' : ActorMethod<[], bigint>,
  /**
   * / Returns an earnings summary for the calling principal.
   * / Sums splits where role == "creator" or role == "seller".
   */
  'getMyEarnings' : ActorMethod<[], EarningsSummary>,
  /**
   * / Returns all purchases made by the calling principal.
   */
  'getMyPurchases' : ActorMethod<[], Array<PurchaseRecord>>,
  'getMyRole' : ActorMethod<[], UserRole>,
  /**
   * / Returns transactions where p appears in any split's principal.
   */
  'getMyTransactions' : ActorMethod<[Principal], Array<Transaction>>,
  'getOfferHistory' : ActorMethod<[bigint], Array<Offer>>,
  'getOffers' : ActorMethod<
    [bigint],
    { 'ok' : Array<Offer> } |
      { 'err' : string }
  >,
  /**
   * / Returns or creates a UserWallet for the caller with an empty btcAddress.
   * / Does NOT call the Bitcoin API — address generation is deferred to createDepositAddress().
   */
  'getOrCreateUserWallet' : ActorMethod<[], UserWallet>,
  /**
   * / Returns the caller's BTC deposit address as their payment address.
   * / All payments are in BTC — no internal payment terminology exposed.
   * / Returns #err if address has not been derived yet (call getUserDepositAddress first).
   */
  'getPaymentAddress' : ActorMethod<[], { 'ok' : string } | { 'err' : string }>,
  'getPokemonSets' : ActorMethod<[], Array<TcgSet>>,
  'getPriceHistory' : ActorMethod<[string], Array<PricePoint>>,
  /**
   * / Returns ALL price points for a clip, sorted chronologically (oldest first).
   * / This is the primary endpoint for rendering complete chart data.
   */
  'getPriceHistoryFull' : ActorMethod<[string], Array<PricePoint>>,
  /**
   * / Returns summary statistics for a clip's sales history.
   * / Useful for chart header stats (total sold, price range, latest activity).
   */
  'getPriceHistorySummary' : ActorMethod<[string], PriceHistorySummary>,
  'getReleases' : ActorMethod<[], Array<Release>>,
  'getSetById' : ActorMethod<[bigint], [] | [TcgSet]>,
  'getSetBySlug' : ActorMethod<[string], [] | [TcgSet]>,
  'getSets' : ActorMethod<[], Array<TcgSet>>,
  'getSetsByCategory' : ActorMethod<[string], Array<TcgSet>>,
  'getTop10ByMarketCap' : ActorMethod<[], Array<MarketCapEntry>>,
  /**
   * / Returns all transactions newest-first.
   */
  'getTransactionHistory' : ActorMethod<[], Array<Transaction>>,
  /**
   * / Get trending hashtags sorted by like score descending.
   * / Returns (tag, post_count) pairs.
   */
  'getTrendingHashtags' : ActorMethod<[], Array<[string, bigint]>>,
  /**
   * / Get trending hashtags with a hot flag.
   * / Returns (tag, post_count, is_hot) — is_hot is true for tags in the top 3 by like score.
   */
  'getTrendingHashtagsWithHotFlag' : ActorMethod<
    [],
    Array<[string, bigint, boolean]>
  >,
  'getUserCollectibles' : ActorMethod<[Principal], Array<Collectible>>,
  /**
   * / Returns the caller's unique ckBTC deposit address.
   * / If the wallet has a valid cached address, returns it immediately.
   * / If the address is empty or invalid, calls createDepositAddress() once and returns its result.
   * / Never retries — one attempt at most.
   * / Logs: caller principal, cached address result, and any errors.
   */
  'getUserDepositAddress' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Returns all deposits (pending and confirmed) for the caller.
   */
  'getUserDeposits' : ActorMethod<[], Array<Deposit>>,
  'getUserPacks' : ActorMethod<[Principal], Array<Pack>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / Retrieve raw video/preview blob data by asset_id.
   */
  'getVideoBlob' : ActorMethod<[string], [] | [VideoAsset]>,
  /**
   * / Initialize bonding curve state for a newly created clip.
   * / Only callable by the clip's creator.
   */
  'initBondingCurve' : ActorMethod<
    [string],
    { 'ok' : BondingCurveState } |
      { 'err' : string }
  >,
  'isAdmin' : ActorMethod<[], boolean>,
  /**
   * / Like a clip. Returns new like_count on success.
   * / Returns #err with a message on rate-limit, duplicate like, or account-too-new.
   */
  'likeClip' : ActorMethod<[string], { 'ok' : bigint } | { 'err' : string }>,
  'makeOffer' : ActorMethod<
    [bigint, number],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'openPack' : ActorMethod<[string], PackOpenResult>,
  /**
   * / Process a $1 mint fee deducted from creator's in-app balance → platform.
   * / Returns the internal transaction ID.
   */
  'processClipMint' : ActorMethod<[Principal], bigint>,
  /**
   * / Process a bonding curve copy sale via in-app balance.
   * / 95% to creator, 5% to platform — deducted from buyer's balance.
   */
  'processCopySale' : ActorMethod<
    [string, Principal, Principal, number],
    bigint
  >,
  /**
   * / Process a secondary trade via in-app balance.
   * / 4% to original creator, 1% to platform, 95% to seller — deducted from buyer's balance.
   */
  'processSecondaryTrade' : ActorMethod<
    [string, Principal, Principal, Principal, number],
    bigint
  >,
  /**
   * / Process a copy sale deducting buyer's wallet balance and crediting creator.
   */
  'processWalletCopySale' : ActorMethod<
    [string, Principal, number],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  /**
   * / Process a $1 mint fee deducting from user's in-app wallet balance.
   * / Returns #err("insufficient balance") if user cannot afford it.
   */
  'processWalletMint' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  /**
   * / Process a secondary trade deducting buyer and crediting seller + creator.
   */
  'processWalletSecondaryTrade' : ActorMethod<
    [string, Principal, Principal, number],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  /**
   * / Process a BTC withdrawal from the caller's in-app balance to an external BTC address.
   * / Deducts balance immediately to prevent double-spend; refunds on failure.
   * / Returns #ok("sent") on success, #err(reason) on failure.
   */
  'processWithdrawal' : ActorMethod<
    [bigint, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Buy a copy of a clip. Assigns an edition number, stores the purchase as #pending,
   * / and promotes all purchases to #minted when all 1000 copies are sold.
   */
  'recordPurchase' : ActorMethod<
    [string, number],
    { 'ok' : PurchaseRecord } |
      { 'err' : string }
  >,
  /**
   * / Record a video hash for the caller. Returns #err("duplicate") if the hash
   * / was already submitted by any user, otherwise records it and returns #ok(true).
   */
  'recordVideoHash' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  /**
   * / Clears the caller's cached BTC deposit address without re-deriving.
   * / The next call to getUserDepositAddress() will trigger createDepositAddress().
   */
  'resetUserDepositAddress' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchSetsByName' : ActorMethod<[string], Array<TcgSet>>,
  /**
   * / Admin: update the BTC/USD rate used for e8s conversions.
   */
  'setBtcRate' : ActorMethod<[number], undefined>,
  'toggleCardActive' : ActorMethod<[bigint], undefined>,
  'toggleCardSupported' : ActorMethod<[bigint], undefined>,
  'toggleCategoryActive' : ActorMethod<[bigint], undefined>,
  'toggleSetActive' : ActorMethod<[bigint], undefined>,
  'updateCard' : ActorMethod<[UpdateTcgCardInput], TcgCard>,
  'updateCategory' : ActorMethod<[UpdateTcgCategoryInput], TcgCategory>,
  'updateSet' : ActorMethod<[UpdateTcgSetInput], TcgSet>,
  /**
   * / Upload a raw preview clip blob (short 2s muted mp4). Returns asset_id to use as preview_loop_url.
   */
  'uploadPreviewBlob' : ActorMethod<[Uint8Array, string], string>,
  /**
   * / Upload a raw HD video blob (mp4). Returns asset_id to use as video_file_url.
   */
  'uploadVideoBlob' : ActorMethod<[Uint8Array, string], string>,
  /**
   * / Fire-and-forget wallet initialization on login.
   * / Creates the wallet record if it doesn't exist (with empty btcAddress).
   * / Does NOT call the Bitcoin API — address generation is deferred to createDepositAddress().
   */
  'warmupDepositAddress' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];