export interface MintMomentSetRank {
  id: string;
  title: string;
  creator: string;
  coverImageUrl: string;
  previewClipUrl?: string;
  description: string;
  totalPacks: number;
  remainingPacks: number;
  pricePerPack: number;
  totalVolume: number;
  salesCount: number;
  nftTrades: number;
  uniqueCollectors: number;
  listedAt: number;
  recentSales: { itemTitle: string; priceUsd: number; timeAgo: string }[];
  // Engagement fields
  packOpens: number;
  previewPlays: number;
  previewReplays: number;
  tapExpansions: number;
  videoCompletionRate: number;
  recentActivityVelocity: number;
  trendingTag: boolean;
}

export function computeEngagementScore(
  set: MintMomentSetRank,
  nowMs: number = Date.now(),
): number {
  const ageMs = nowMs - set.listedAt;
  const ageH = ageMs / 3600000;
  const recencyMult = ageH <= 48 ? 1.5 : ageH <= 168 ? 1.15 : 1.0;

  const base =
    set.packOpens * 12 +
    set.uniqueCollectors * 15 +
    set.previewPlays * 4 +
    set.previewReplays * 8 +
    set.tapExpansions * 5 +
    set.videoCompletionRate * 200 +
    set.recentActivityVelocity * 50 +
    set.salesCount * 6 +
    set.totalVolume * 0.05;

  return base * recencyMult;
}

// Legacy scoring kept for backward compat
export function computeScore(
  set: MintMomentSetRank,
  nowMs: number = Date.now(),
): number {
  return computeEngagementScore(set, nowMs);
}

const COVER_IMAGES = [
  "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&q=80",
  "https://images.unsplash.com/photo-1492551557933-34265f7af79e?w=400&q=80",
  "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=400&q=80",
  "https://images.unsplash.com/photo-1504274066651-8d31a536b11a?w=400&q=80",
  "https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=400&q=80",
  "https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?w=400&q=80",
  "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=400&q=80",
  "https://images.unsplash.com/photo-1433360405326-e50f909805b3?w=400&q=80",
];

const now = Date.now();
const h = 3600000;
const d = 86400000;

function hoursAgoMs(n: number) {
  return now - n * h;
}
function daysAgoMs(n: number) {
  return now - n * d;
}

export const MOCK_DISCOVER_SETS: MintMomentSetRank[] = [
  // ── TOP TIER: high engagement, established momentum ─────────────────────
  {
    id: "ds001",
    title: "Morning Coffee",
    creator: "@erin",
    coverImageUrl: COVER_IMAGES[0],
    description:
      "A quiet morning ritual captured in 9 stills and one 30-second film. The scent of espresso in soft winter light.",
    totalPacks: 100,
    remainingPacks: 8,
    pricePerPack: 3.5,
    totalVolume: 1834,
    salesCount: 312,
    nftTrades: 87,
    uniqueCollectors: 74,
    listedAt: daysAgoMs(45),
    recentSales: [
      { itemTitle: "📦 Pack opened", priceUsd: 3.5, timeAgo: "2h ago" },
      { itemTitle: "📦 Pack opened", priceUsd: 3.5, timeAgo: "5h ago" },
      { itemTitle: "🔁 NFT trade", priceUsd: 18, timeAgo: "1d ago" },
    ],
    packOpens: 387,
    previewPlays: 1920,
    previewReplays: 580,
    tapExpansions: 760,
    videoCompletionRate: 0.88,
    recentActivityVelocity: 52,
    trendingTag: true,
  },
  {
    id: "ds002",
    title: "Sunset Ride",
    creator: "@coastaldrift",
    coverImageUrl: COVER_IMAGES[1],
    description:
      "Long coastal highway, golden hour from the saddle. 9 frames of pure motion.",
    totalPacks: 80,
    remainingPacks: 12,
    pricePerPack: 4.0,
    totalVolume: 1640,
    salesCount: 280,
    nftTrades: 74,
    uniqueCollectors: 63,
    listedAt: daysAgoMs(38),
    recentSales: [
      { itemTitle: "📦 Pack opened", priceUsd: 4.0, timeAgo: "3h ago" },
      { itemTitle: "🔁 NFT trade", priceUsd: 22, timeAgo: "8h ago" },
    ],
    packOpens: 342,
    previewPlays: 1740,
    previewReplays: 495,
    tapExpansions: 680,
    videoCompletionRate: 0.82,
    recentActivityVelocity: 44,
    trendingTag: true,
  },
  {
    id: "ds003",
    title: "Golden Hour",
    creator: "@lightchaser",
    coverImageUrl: COVER_IMAGES[4],
    description:
      "That 40-minute window before dusk where everything turns amber. Chased across three cities.",
    totalPacks: 120,
    remainingPacks: 5,
    pricePerPack: 3.0,
    totalVolume: 1560,
    salesCount: 340,
    nftTrades: 91,
    uniqueCollectors: 82,
    listedAt: daysAgoMs(60),
    recentSales: [
      { itemTitle: "📦 Pack opened", priceUsd: 3.0, timeAgo: "1h ago" },
      { itemTitle: "📦 Pack opened", priceUsd: 3.0, timeAgo: "4h ago" },
      { itemTitle: "🔁 NFT trade", priceUsd: 14, timeAgo: "12h ago" },
    ],
    packOpens: 371,
    previewPlays: 1650,
    previewReplays: 512,
    tapExpansions: 720,
    videoCompletionRate: 0.79,
    recentActivityVelocity: 38,
    trendingTag: true,
  },
  {
    id: "ds004",
    title: "Late Night Drive",
    creator: "neon_rider.icp",
    coverImageUrl: COVER_IMAGES[1],
    description:
      "City after midnight — sodium lights, empty boulevards, the hum of the engine.",
    totalPacks: 75,
    remainingPacks: 0,
    pricePerPack: 5.0,
    totalVolume: 1420,
    salesCount: 218,
    nftTrades: 66,
    uniqueCollectors: 55,
    listedAt: daysAgoMs(30),
    recentSales: [
      { itemTitle: "🔁 NFT trade", priceUsd: 28, timeAgo: "6h ago" },
      { itemTitle: "🔁 NFT trade", priceUsd: 19, timeAgo: "1d ago" },
    ],
    packOpens: 298,
    previewPlays: 1480,
    previewReplays: 430,
    tapExpansions: 590,
    videoCompletionRate: 0.86,
    recentActivityVelocity: 28,
    trendingTag: true,
  },
  {
    id: "ds005",
    title: "Ocean Mist",
    creator: "@wavecatcher",
    coverImageUrl: COVER_IMAGES[2],
    description:
      "Pre-dawn at the shore. Cold sand, salt air, and waves that never stop coming.",
    totalPacks: 90,
    remainingPacks: 22,
    pricePerPack: 3.5,
    totalVolume: 1204,
    salesCount: 198,
    nftTrades: 54,
    uniqueCollectors: 47,
    listedAt: daysAgoMs(20),
    recentSales: [
      { itemTitle: "📦 Pack opened", priceUsd: 3.5, timeAgo: "30m ago" },
      { itemTitle: "📦 Pack opened", priceUsd: 3.5, timeAgo: "2h ago" },
    ],
    packOpens: 263,
    previewPlays: 1320,
    previewReplays: 378,
    tapExpansions: 510,
    videoCompletionRate: 0.74,
    recentActivityVelocity: 35,
    trendingTag: true,
  },
  {
    id: "ds006",
    title: "City Lights",
    creator: "@urbanmoment",
    coverImageUrl: COVER_IMAGES[1],
    description:
      "An upward gaze through glass towers and rain-slicked streets.",
    totalPacks: 60,
    remainingPacks: 14,
    pricePerPack: 4.5,
    totalVolume: 1140,
    salesCount: 176,
    nftTrades: 48,
    uniqueCollectors: 41,
    listedAt: hoursAgoMs(18),
    recentSales: [
      { itemTitle: "📦 Pack opened", priceUsd: 4.5, timeAgo: "45m ago" },
      { itemTitle: "📦 Pack opened", priceUsd: 4.5, timeAgo: "3h ago" },
      { itemTitle: "🔁 NFT trade", priceUsd: 32, timeAgo: "5h ago" },
    ],
    packOpens: 248,
    previewPlays: 1260,
    previewReplays: 398,
    tapExpansions: 550,
    videoCompletionRate: 0.81,
    recentActivityVelocity: 61,
    trendingTag: true,
  },
  {
    id: "ds007",
    title: "First Snow",
    creator: "@winterstudio",
    coverImageUrl: COVER_IMAGES[6],
    description:
      "The day everything goes quiet. First snowfall of the season, documented minute by minute.",
    totalPacks: 110,
    remainingPacks: 31,
    pricePerPack: 3.0,
    totalVolume: 1080,
    salesCount: 204,
    nftTrades: 61,
    uniqueCollectors: 58,
    listedAt: daysAgoMs(14),
    recentSales: [
      { itemTitle: "📦 Pack opened", priceUsd: 3.0, timeAgo: "1h ago" },
      { itemTitle: "📦 Pack opened", priceUsd: 3.0, timeAgo: "6h ago" },
    ],
    packOpens: 231,
    previewPlays: 1180,
    previewReplays: 356,
    tapExpansions: 490,
    videoCompletionRate: 0.76,
    recentActivityVelocity: 32,
    trendingTag: true,
  },
  {
    id: "ds008",
    title: "Bloom",
    creator: "@gardenpath",
    coverImageUrl: COVER_IMAGES[5],
    description:
      "Spring arrives in a single garden over three weeks. Macro stills of petals breaking open.",
    totalPacks: 85,
    remainingPacks: 18,
    pricePerPack: 3.5,
    totalVolume: 960,
    salesCount: 167,
    nftTrades: 43,
    uniqueCollectors: 39,
    listedAt: daysAgoMs(25),
    recentSales: [
      { itemTitle: "📦 Pack opened", priceUsd: 3.5, timeAgo: "2h ago" },
      { itemTitle: "🔁 NFT trade", priceUsd: 16, timeAgo: "1d ago" },
    ],
    packOpens: 214,
    previewPlays: 1040,
    previewReplays: 290,
    tapExpansions: 440,
    videoCompletionRate: 0.7,
    recentActivityVelocity: 24,
    trendingTag: false,
  },
  {
    id: "ds009",
    title: "Mountain Top",
    creator: "@altitudelab",
    coverImageUrl: COVER_IMAGES[0],
    description:
      "Summit series: nine peaks, nine Moments. The thin air makes everything sharper.",
    totalPacks: 70,
    remainingPacks: 9,
    pricePerPack: 5.0,
    totalVolume: 940,
    salesCount: 142,
    nftTrades: 37,
    uniqueCollectors: 33,
    listedAt: daysAgoMs(50),
    recentSales: [
      { itemTitle: "🔁 NFT trade", priceUsd: 24, timeAgo: "4h ago" },
      { itemTitle: "📦 Pack opened", priceUsd: 5.0, timeAgo: "10h ago" },
    ],
    packOpens: 193,
    previewPlays: 920,
    previewReplays: 248,
    tapExpansions: 380,
    videoCompletionRate: 0.68,
    recentActivityVelocity: 18,
    trendingTag: false,
  },
  {
    id: "ds010",
    title: "Midnight Run",
    creator: "@runnersguild",
    coverImageUrl: COVER_IMAGES[6],
    description:
      "Running through the city at 2am. Breath visible. Pavement slick. Pure focus.",
    totalPacks: 65,
    remainingPacks: 11,
    pricePerPack: 4.0,
    totalVolume: 876,
    salesCount: 138,
    nftTrades: 35,
    uniqueCollectors: 30,
    listedAt: daysAgoMs(18),
    recentSales: [
      { itemTitle: "📦 Pack opened", priceUsd: 4.0, timeAgo: "1h ago" },
      { itemTitle: "📦 Pack opened", priceUsd: 4.0, timeAgo: "7h ago" },
    ],
    packOpens: 178,
    previewPlays: 860,
    previewReplays: 220,
    tapExpansions: 340,
    videoCompletionRate: 0.65,
    recentActivityVelocity: 22,
    trendingTag: false,
  },
  // ── RISING FAST: recently listed with high velocity ──────────────────────
  {
    id: "ds011",
    title: "Neon Arcade",
    creator: "@pixelwave",
    coverImageUrl: COVER_IMAGES[3],
    description:
      "Retro arcades at 1am. The glow, the sound, the quarters. Nine frames you can feel.",
    totalPacks: 40,
    remainingPacks: 35,
    pricePerPack: 4.0,
    totalVolume: 28,
    salesCount: 7,
    nftTrades: 2,
    uniqueCollectors: 6,
    listedAt: hoursAgoMs(14),
    recentSales: [
      { itemTitle: "📦 Pack opened", priceUsd: 4.0, timeAgo: "40m ago" },
      { itemTitle: "📦 Pack opened", priceUsd: 4.0, timeAgo: "2h ago" },
    ],
    packOpens: 38,
    previewPlays: 412,
    previewReplays: 180,
    tapExpansions: 210,
    videoCompletionRate: 0.91,
    recentActivityVelocity: 78,
    trendingTag: true,
  },
  {
    id: "ds012",
    title: "Rain Window",
    creator: "@quietframe",
    coverImageUrl: COVER_IMAGES[3],
    description:
      "Watching the city through a rain-streaked window from the inside.",
    totalPacks: 55,
    remainingPacks: 48,
    pricePerPack: 4.0,
    totalVolume: 36,
    salesCount: 9,
    nftTrades: 2,
    uniqueCollectors: 8,
    listedAt: hoursAgoMs(8),
    recentSales: [
      { itemTitle: "📦 Pack opened", priceUsd: 4.0, timeAgo: "20m ago" },
      { itemTitle: "📦 Pack opened", priceUsd: 4.0, timeAgo: "1h ago" },
    ],
    packOpens: 44,
    previewPlays: 520,
    previewReplays: 210,
    tapExpansions: 240,
    videoCompletionRate: 0.87,
    recentActivityVelocity: 68,
    trendingTag: true,
  },
  {
    id: "ds013",
    title: "Desert Bloom",
    creator: "@aridstudio",
    coverImageUrl: COVER_IMAGES[4],
    description: "After the rain, the desert comes alive for 72 hours.",
    totalPacks: 60,
    remainingPacks: 50,
    pricePerPack: 4.5,
    totalVolume: 22,
    salesCount: 5,
    nftTrades: 1,
    uniqueCollectors: 5,
    listedAt: hoursAgoMs(6),
    recentSales: [
      { itemTitle: "📦 Pack opened", priceUsd: 4.5, timeAgo: "1h ago" },
    ],
    packOpens: 28,
    previewPlays: 380,
    previewReplays: 148,
    tapExpansions: 180,
    videoCompletionRate: 0.84,
    recentActivityVelocity: 55,
    trendingTag: true,
  },
  {
    id: "ds014",
    title: "Empty Stage",
    creator: "@venuedrift",
    coverImageUrl: COVER_IMAGES[6],
    description: "Concert venues before the crowd arrives. Quiet anticipation.",
    totalPacks: 50,
    remainingPacks: 45,
    pricePerPack: 5.0,
    totalVolume: 15,
    salesCount: 3,
    nftTrades: 1,
    uniqueCollectors: 3,
    listedAt: hoursAgoMs(4),
    recentSales: [
      { itemTitle: "📦 Pack opened", priceUsd: 5.0, timeAgo: "30m ago" },
    ],
    packOpens: 18,
    previewPlays: 290,
    previewReplays: 122,
    tapExpansions: 150,
    videoCompletionRate: 0.93,
    recentActivityVelocity: 47,
    trendingTag: true,
  },
  // ── MID TIER ─────────────────────────────────────────────────────────────
  {
    id: "ds015",
    title: "Tokyo Alley",
    creator: "@streetframe.jp",
    coverImageUrl: COVER_IMAGES[1],
    description: "A single alley in Shinjuku at 11pm. Neon vs. rain.",
    totalPacks: 50,
    remainingPacks: 7,
    pricePerPack: 6.0,
    totalVolume: 748,
    salesCount: 96,
    nftTrades: 42,
    uniqueCollectors: 36,
    listedAt: daysAgoMs(28),
    recentSales: [
      { itemTitle: "🔁 NFT trade", priceUsd: 38, timeAgo: "2h ago" },
      { itemTitle: "📦 Pack opened", priceUsd: 6.0, timeAgo: "9h ago" },
    ],
    packOpens: 162,
    previewPlays: 740,
    previewReplays: 195,
    tapExpansions: 310,
    videoCompletionRate: 0.71,
    recentActivityVelocity: 20,
    trendingTag: true,
  },
  {
    id: "ds016",
    title: "Harvest Light",
    creator: "@fieldsong",
    coverImageUrl: COVER_IMAGES[4],
    description:
      "October fields, amber skies, and the last warmth before the freeze.",
    totalPacks: 90,
    remainingPacks: 34,
    pricePerPack: 3.5,
    totalVolume: 710,
    salesCount: 118,
    nftTrades: 27,
    uniqueCollectors: 25,
    listedAt: daysAgoMs(40),
    recentSales: [
      { itemTitle: "📦 Pack opened", priceUsd: 3.5, timeAgo: "6h ago" },
    ],
    packOpens: 148,
    previewPlays: 680,
    previewReplays: 162,
    tapExpansions: 280,
    videoCompletionRate: 0.63,
    recentActivityVelocity: 12,
    trendingTag: false,
  },
  {
    id: "ds017",
    title: "Sunday Market",
    creator: "@marketlight",
    coverImageUrl: COVER_IMAGES[5],
    description: "Farmers market, 8am. Color, texture, community.",
    totalPacks: 75,
    remainingPacks: 28,
    pricePerPack: 3.0,
    totalVolume: 634,
    salesCount: 98,
    nftTrades: 21,
    uniqueCollectors: 20,
    listedAt: daysAgoMs(12),
    recentSales: [
      { itemTitle: "📦 Pack opened", priceUsd: 3.0, timeAgo: "4h ago" },
    ],
    packOpens: 138,
    previewPlays: 620,
    previewReplays: 148,
    tapExpansions: 255,
    videoCompletionRate: 0.6,
    recentActivityVelocity: 16,
    trendingTag: false,
  },
  {
    id: "ds018",
    title: "Rooftop Session",
    creator: "@skylineview",
    coverImageUrl: COVER_IMAGES[1],
    description: "Music on a downtown rooftop as the city lights come on.",
    totalPacks: 45,
    remainingPacks: 15,
    pricePerPack: 5.0,
    totalVolume: 612,
    salesCount: 84,
    nftTrades: 32,
    uniqueCollectors: 29,
    listedAt: daysAgoMs(16),
    recentSales: [
      { itemTitle: "🔁 NFT trade", priceUsd: 27, timeAgo: "3h ago" },
    ],
    packOpens: 124,
    previewPlays: 580,
    previewReplays: 138,
    tapExpansions: 230,
    videoCompletionRate: 0.72,
    recentActivityVelocity: 14,
    trendingTag: false,
  },
  {
    id: "ds019",
    title: "Tide Pool",
    creator: "@tidewatcher",
    coverImageUrl: COVER_IMAGES[2],
    description:
      "Miniature ecosystems revealed at low tide. Nine frames, nine worlds.",
    totalPacks: 65,
    remainingPacks: 23,
    pricePerPack: 4.0,
    totalVolume: 580,
    salesCount: 88,
    nftTrades: 19,
    uniqueCollectors: 18,
    listedAt: daysAgoMs(33),
    recentSales: [
      { itemTitle: "📦 Pack opened", priceUsd: 4.0, timeAgo: "8h ago" },
    ],
    packOpens: 118,
    previewPlays: 540,
    previewReplays: 124,
    tapExpansions: 210,
    videoCompletionRate: 0.58,
    recentActivityVelocity: 10,
    trendingTag: false,
  },
  {
    id: "ds020",
    title: "Foggy Morning",
    creator: "@mist.frames",
    coverImageUrl: COVER_IMAGES[2],
    description: "When the valley fills with fog before the sun burns it away.",
    totalPacks: 80,
    remainingPacks: 26,
    pricePerPack: 3.0,
    totalVolume: 800,
    salesCount: 128,
    nftTrades: 29,
    uniqueCollectors: 27,
    listedAt: daysAgoMs(22),
    recentSales: [
      { itemTitle: "📦 Pack opened", priceUsd: 3.0, timeAgo: "3h ago" },
    ],
    packOpens: 154,
    previewPlays: 700,
    previewReplays: 172,
    tapExpansions: 295,
    videoCompletionRate: 0.66,
    recentActivityVelocity: 18,
    trendingTag: false,
  },
  {
    id: "ds021",
    title: "Street Rain",
    creator: "@wetpavement",
    coverImageUrl: COVER_IMAGES[3],
    description:
      "Nine portraits taken in the ten minutes after the storm passed.",
    totalPacks: 55,
    remainingPacks: 19,
    pricePerPack: 4.5,
    totalVolume: 560,
    salesCount: 82,
    nftTrades: 22,
    uniqueCollectors: 21,
    listedAt: daysAgoMs(27),
    recentSales: [
      { itemTitle: "📦 Pack opened", priceUsd: 4.5, timeAgo: "5h ago" },
    ],
    packOpens: 112,
    previewPlays: 510,
    previewReplays: 118,
    tapExpansions: 195,
    videoCompletionRate: 0.62,
    recentActivityVelocity: 11,
    trendingTag: false,
  },
  {
    id: "ds022",
    title: "Porch Light",
    creator: "@front_step",
    coverImageUrl: COVER_IMAGES[0],
    description: "Neighborhood porches after dark. Quietly watched lives.",
    totalPacks: 70,
    remainingPacks: 30,
    pricePerPack: 3.5,
    totalVolume: 540,
    salesCount: 78,
    nftTrades: 18,
    uniqueCollectors: 17,
    listedAt: daysAgoMs(31),
    recentSales: [],
    packOpens: 108,
    previewPlays: 490,
    previewReplays: 112,
    tapExpansions: 188,
    videoCompletionRate: 0.57,
    recentActivityVelocity: 8,
    trendingTag: false,
  },
  {
    id: "ds023",
    title: "Candle Hour",
    creator: "@waxroom",
    coverImageUrl: COVER_IMAGES[4],
    description:
      "Dinner table before guests arrive. Warmth, anticipation, texture.",
    totalPacks: 50,
    remainingPacks: 21,
    pricePerPack: 5.0,
    totalVolume: 520,
    salesCount: 72,
    nftTrades: 20,
    uniqueCollectors: 19,
    listedAt: daysAgoMs(35),
    recentSales: [
      { itemTitle: "🔁 NFT trade", priceUsd: 21, timeAgo: "6h ago" },
    ],
    packOpens: 104,
    previewPlays: 465,
    previewReplays: 108,
    tapExpansions: 180,
    videoCompletionRate: 0.68,
    recentActivityVelocity: 9,
    trendingTag: false,
  },
  {
    id: "ds024",
    title: "Glass Bridge",
    creator: "@architectframe",
    coverImageUrl: COVER_IMAGES[6],
    description:
      "Brutalist bridge over a river gorge. Concrete and sky and movement.",
    totalPacks: 60,
    remainingPacks: 17,
    pricePerPack: 4.0,
    totalVolume: 500,
    salesCount: 68,
    nftTrades: 16,
    uniqueCollectors: 15,
    listedAt: daysAgoMs(42),
    recentSales: [],
    packOpens: 98,
    previewPlays: 445,
    previewReplays: 102,
    tapExpansions: 170,
    videoCompletionRate: 0.55,
    recentActivityVelocity: 7,
    trendingTag: false,
  },
  {
    id: "ds025",
    title: "Vinyl Bar",
    creator: "@spinroom",
    coverImageUrl: COVER_IMAGES[5],
    description:
      "A record bar in Brooklyn. Nine angles on one humid Saturday night.",
    totalPacks: 40,
    remainingPacks: 12,
    pricePerPack: 6.0,
    totalVolume: 480,
    salesCount: 62,
    nftTrades: 24,
    uniqueCollectors: 22,
    listedAt: daysAgoMs(19),
    recentSales: [
      { itemTitle: "🔁 NFT trade", priceUsd: 34, timeAgo: "8h ago" },
    ],
    packOpens: 92,
    previewPlays: 420,
    previewReplays: 95,
    tapExpansions: 162,
    videoCompletionRate: 0.73,
    recentActivityVelocity: 13,
    trendingTag: true,
  },
  {
    id: "ds026",
    title: "Kitchen Table",
    creator: "@homescenes",
    coverImageUrl: COVER_IMAGES[0],
    description:
      "Sunday breakfast at the same table, different week, different light.",
    totalPacks: 65,
    remainingPacks: 24,
    pricePerPack: 3.0,
    totalVolume: 462,
    salesCount: 76,
    nftTrades: 14,
    uniqueCollectors: 13,
    listedAt: daysAgoMs(48),
    recentSales: [],
    packOpens: 94,
    previewPlays: 395,
    previewReplays: 87,
    tapExpansions: 152,
    videoCompletionRate: 0.54,
    recentActivityVelocity: 6,
    trendingTag: false,
  },
  {
    id: "ds027",
    title: "Shoreline",
    creator: "@tideswept",
    coverImageUrl: COVER_IMAGES[2],
    description:
      "The exact line where land ends. Photographed over one spring tide.",
    totalPacks: 70,
    remainingPacks: 29,
    pricePerPack: 4.0,
    totalVolume: 440,
    salesCount: 64,
    nftTrades: 13,
    uniqueCollectors: 12,
    listedAt: daysAgoMs(55),
    recentSales: [],
    packOpens: 88,
    previewPlays: 370,
    previewReplays: 82,
    tapExpansions: 145,
    videoCompletionRate: 0.52,
    recentActivityVelocity: 5,
    trendingTag: false,
  },
  {
    id: "ds028",
    title: "Underpass",
    creator: "@concretepoetry",
    coverImageUrl: COVER_IMAGES[3],
    description:
      "The social life of a highway underpass. Skaters, murals, pigeons.",
    totalPacks: 45,
    remainingPacks: 16,
    pricePerPack: 5.0,
    totalVolume: 420,
    salesCount: 58,
    nftTrades: 17,
    uniqueCollectors: 16,
    listedAt: daysAgoMs(24),
    recentSales: [
      { itemTitle: "📦 Pack opened", priceUsd: 5.0, timeAgo: "11h ago" },
    ],
    packOpens: 84,
    previewPlays: 355,
    previewReplays: 78,
    tapExpansions: 138,
    videoCompletionRate: 0.64,
    recentActivityVelocity: 10,
    trendingTag: false,
  },
  {
    id: "ds029",
    title: "Platform 9",
    creator: "@transitlab",
    coverImageUrl: COVER_IMAGES[1],
    description: "A busy metro station observed from one spot for one hour.",
    totalPacks: 80,
    remainingPacks: 35,
    pricePerPack: 3.5,
    totalVolume: 400,
    salesCount: 60,
    nftTrades: 11,
    uniqueCollectors: 11,
    listedAt: daysAgoMs(37),
    recentSales: [],
    packOpens: 80,
    previewPlays: 340,
    previewReplays: 74,
    tapExpansions: 132,
    videoCompletionRate: 0.5,
    recentActivityVelocity: 5,
    trendingTag: false,
  },
  {
    id: "ds030",
    title: "Salt Flats",
    creator: "@whitehorizon",
    coverImageUrl: COVER_IMAGES[4],
    description: "Bonneville in August. The geometry of emptiness.",
    totalPacks: 55,
    remainingPacks: 22,
    pricePerPack: 4.5,
    totalVolume: 385,
    salesCount: 56,
    nftTrades: 12,
    uniqueCollectors: 11,
    listedAt: daysAgoMs(44),
    recentSales: [],
    packOpens: 76,
    previewPlays: 320,
    previewReplays: 70,
    tapExpansions: 125,
    videoCompletionRate: 0.61,
    recentActivityVelocity: 7,
    trendingTag: false,
  },
  {
    id: "ds031",
    title: "Corner Store",
    creator: "@neighborhoodlens",
    coverImageUrl: COVER_IMAGES[5],
    description:
      "A 24-hour deli in the Bronx. The cast of characters changes by hour.",
    totalPacks: 60,
    remainingPacks: 28,
    pricePerPack: 4.0,
    totalVolume: 370,
    salesCount: 54,
    nftTrades: 10,
    uniqueCollectors: 10,
    listedAt: daysAgoMs(29),
    recentSales: [],
    packOpens: 72,
    previewPlays: 305,
    previewReplays: 66,
    tapExpansions: 118,
    videoCompletionRate: 0.56,
    recentActivityVelocity: 6,
    trendingTag: false,
  },
  {
    id: "ds032",
    title: "Window Seat",
    creator: "@flightframe",
    coverImageUrl: COVER_IMAGES[6],
    description:
      "Flight over the central US. Clouds from above, towns from above.",
    totalPacks: 50,
    remainingPacks: 21,
    pricePerPack: 4.5,
    totalVolume: 360,
    salesCount: 52,
    nftTrades: 11,
    uniqueCollectors: 10,
    listedAt: daysAgoMs(36),
    recentSales: [],
    packOpens: 68,
    previewPlays: 290,
    previewReplays: 63,
    tapExpansions: 112,
    videoCompletionRate: 0.59,
    recentActivityVelocity: 5,
    trendingTag: false,
  },
  {
    id: "ds033",
    title: "Library Stack",
    creator: "@archivecrawl",
    coverImageUrl: COVER_IMAGES[0],
    description: "The stacks at 4pm. Nobody there but the books and the dust.",
    totalPacks: 40,
    remainingPacks: 18,
    pricePerPack: 4.0,
    totalVolume: 348,
    salesCount: 50,
    nftTrades: 9,
    uniqueCollectors: 9,
    listedAt: daysAgoMs(53),
    recentSales: [],
    packOpens: 64,
    previewPlays: 276,
    previewReplays: 60,
    tapExpansions: 106,
    videoCompletionRate: 0.53,
    recentActivityVelocity: 4,
    trendingTag: false,
  },
  {
    id: "ds034",
    title: "Laundromat",
    creator: "@cycleframe",
    coverImageUrl: COVER_IMAGES[2],
    description: "Portrait of a laundromat at 10pm. Light, waiting, tumbling.",
    totalPacks: 45,
    remainingPacks: 20,
    pricePerPack: 3.5,
    totalVolume: 334,
    salesCount: 48,
    nftTrades: 9,
    uniqueCollectors: 8,
    listedAt: daysAgoMs(41),
    recentSales: [],
    packOpens: 60,
    previewPlays: 262,
    previewReplays: 57,
    tapExpansions: 100,
    videoCompletionRate: 0.5,
    recentActivityVelocity: 4,
    trendingTag: false,
  },
  {
    id: "ds035",
    title: "Parking Lot",
    creator: "@carbonstudy",
    coverImageUrl: COVER_IMAGES[1],
    description: "Empty mall parking lot at 7am. Lines, carts, a single crow.",
    totalPacks: 35,
    remainingPacks: 16,
    pricePerPack: 4.0,
    totalVolume: 320,
    salesCount: 46,
    nftTrades: 8,
    uniqueCollectors: 8,
    listedAt: daysAgoMs(46),
    recentSales: [],
    packOpens: 56,
    previewPlays: 248,
    previewReplays: 54,
    tapExpansions: 95,
    videoCompletionRate: 0.48,
    recentActivityVelocity: 3,
    trendingTag: false,
  },
  {
    id: "ds036",
    title: "Bakery Open",
    creator: "@dawnshift",
    coverImageUrl: COVER_IMAGES[4],
    description:
      "The first 90 minutes of a bakery's morning. Flour, fire, routine.",
    totalPacks: 50,
    remainingPacks: 23,
    pricePerPack: 3.5,
    totalVolume: 308,
    salesCount: 44,
    nftTrades: 8,
    uniqueCollectors: 7,
    listedAt: daysAgoMs(49),
    recentSales: [],
    packOpens: 52,
    previewPlays: 234,
    previewReplays: 51,
    tapExpansions: 90,
    videoCompletionRate: 0.58,
    recentActivityVelocity: 4,
    trendingTag: false,
  },
  {
    id: "ds037",
    title: "Greenhouse",
    creator: "@leafstudio",
    coverImageUrl: COVER_IMAGES[5],
    description:
      "A commercial greenhouse in winter. Controlled summer in frozen air.",
    totalPacks: 55,
    remainingPacks: 26,
    pricePerPack: 3.0,
    totalVolume: 295,
    salesCount: 42,
    nftTrades: 7,
    uniqueCollectors: 7,
    listedAt: daysAgoMs(52),
    recentSales: [],
    packOpens: 48,
    previewPlays: 220,
    previewReplays: 48,
    tapExpansions: 85,
    videoCompletionRate: 0.56,
    recentActivityVelocity: 3,
    trendingTag: false,
  },
  {
    id: "ds038",
    title: "Pawn Shop",
    creator: "@secondshelve",
    coverImageUrl: COVER_IMAGES[3],
    description: "Objects with histories. A pawn shop in South Phoenix.",
    totalPacks: 40,
    remainingPacks: 19,
    pricePerPack: 4.5,
    totalVolume: 282,
    salesCount: 40,
    nftTrades: 8,
    uniqueCollectors: 7,
    listedAt: daysAgoMs(57),
    recentSales: [],
    packOpens: 44,
    previewPlays: 208,
    previewReplays: 45,
    tapExpansions: 80,
    videoCompletionRate: 0.55,
    recentActivityVelocity: 3,
    trendingTag: false,
  },
  {
    id: "ds039",
    title: "Diner Counter",
    creator: "@seatfour",
    coverImageUrl: COVER_IMAGES[0],
    description: "Nine hours at the counter of an old Route 66 diner.",
    totalPacks: 45,
    remainingPacks: 22,
    pricePerPack: 3.5,
    totalVolume: 268,
    salesCount: 38,
    nftTrades: 7,
    uniqueCollectors: 6,
    listedAt: daysAgoMs(62),
    recentSales: [],
    packOpens: 40,
    previewPlays: 195,
    previewReplays: 42,
    tapExpansions: 75,
    videoCompletionRate: 0.53,
    recentActivityVelocity: 3,
    trendingTag: false,
  },
  {
    id: "ds040",
    title: "Night Ferry",
    creator: "@crosswater",
    coverImageUrl: COVER_IMAGES[2],
    description: "Puget Sound at midnight. Ferry lights on black water.",
    totalPacks: 50,
    remainingPacks: 24,
    pricePerPack: 4.0,
    totalVolume: 255,
    salesCount: 36,
    nftTrades: 7,
    uniqueCollectors: 6,
    listedAt: daysAgoMs(66),
    recentSales: [],
    packOpens: 36,
    previewPlays: 182,
    previewReplays: 40,
    tapExpansions: 70,
    videoCompletionRate: 0.6,
    recentActivityVelocity: 3,
    trendingTag: false,
  },
  // ── LOWER TIER (ds041–ds070): gradual decline ─────────────────────────────
  ...Array.from({ length: 30 }, (_, i) => {
    const idx = i + 41;
    const titles = [
      "Reservoir",
      "Old Gym",
      "Bus Depot",
      "River Lock",
      "Cargo Hold",
      "Junkyard",
      "Attic Light",
      "Carwash",
      "Drive-In",
      "Train Yard",
      "Loading Dock",
      "Stairwell",
      "Boiler Room",
      "Storage Unit",
      "Parking Garage",
      "Waiting Room",
      "Truck Stop",
      "Switching Yard",
      "Cold Room",
      "Scaffold",
      "Utility Closet",
      "Runway Edge",
      "Tarmac",
      "Hangar",
      "Silo",
      "Water Tower",
      "Signal Box",
      "Drainage",
      "Fire Escape",
      "Checkpoint",
    ];
    const creators = [
      "@reservoir.eye",
      "@gymfloor",
      "@busdepot",
      "@riverview",
      "@cargolens",
      "@junkyard.vis",
      "@atticlight",
      "@waxcarwash",
      "@drivein.lens",
      "@trainyardco",
      "@dockframe",
      "@stairwell.vis",
      "@boiler.eye",
      "@storageunit",
      "@structframe",
      "@waitingroom",
      "@truckstop.icp",
      "@switchyard",
      "@coldroom",
      "@scaffoldvis",
      "@utilitylens",
      "@runwayedge",
      "@tarmacframe",
      "@hangerdoor",
      "@siloeye",
      "@watertower",
      "@signalbox",
      "@drainage.vis",
      "@firescape",
      "@checkpoint",
    ];
    const vol = Math.max(5, 245 - i * 7);
    const sales = Math.max(2, 34 - i);
    const collectors = Math.max(1, 6 - Math.floor(i / 6));
    const opens = Math.max(4, 34 - i);
    const plays = Math.max(10, 175 - i * 5);
    const replays = Math.max(4, 38 - i);
    const taps = Math.max(5, 68 - i * 2);
    const vcr = Math.max(0.25, 0.51 - i * 0.008);
    return {
      id: `ds0${idx}`,
      title: titles[i],
      creator: creators[i],
      coverImageUrl: COVER_IMAGES[i % COVER_IMAGES.length],
      description: "A Mint Moment set exploring a specific place and light.",
      totalPacks: 40 + (i % 5) * 10,
      remainingPacks: 15 + (i % 8) * 3,
      pricePerPack: 3.0 + (i % 4) * 0.5,
      totalVolume: vol,
      salesCount: sales,
      nftTrades: Math.max(1, Math.floor(sales / 4)),
      uniqueCollectors: collectors,
      listedAt: daysAgoMs(70 + i * 4),
      recentSales: [],
      packOpens: opens,
      previewPlays: plays,
      previewReplays: replays,
      tapExpansions: taps,
      videoCompletionRate: vcr,
      recentActivityVelocity: Math.max(0, 3 - Math.floor(i / 10)),
      trendingTag: false,
    } satisfies MintMomentSetRank;
  }),
  // ── TAIL (ds071–ds100): minimal activity ─────────────────────────────────
  ...Array.from({ length: 30 }, (_, i) => {
    const idx = i + 71;
    const titles = [
      "Salt Marsh",
      "Coal Bunker",
      "Snowplow Night",
      "Open Sea",
      "Printing Press",
      "Bamboo Grove",
      "Switchback",
      "Wire Fence",
      "Empty Lot",
      "Foghorn",
      "Driftwood",
      "Cold Spring",
      "Quarry Edge",
      "Pier End",
      "Rail Cut",
      "Sand Bar",
      "Stone Wall",
      "Grain Elevator",
      "Culvert",
      "Rock Face",
      "Tide Gate",
      "Ice Road",
      "Ferry Ramp",
      "Canal Lock",
      "Concrete Wall",
      "Landfill Edge",
      "Water Main",
      "Cable Car",
      "Overpass",
      "New Release",
    ];
    const creators = [
      "@saltmarsh",
      "@lastlight.coal",
      "@clearingframe",
      "@bluewater",
      "@pressroom",
      "@bamboogrove",
      "@switchback",
      "@wirefence",
      "@emptylotstudio",
      "@foghorn.vis",
      "@driftwood.icp",
      "@coldspring",
      "@quarryedge",
      "@pier.end",
      "@railcut",
      "@sandbar.vis",
      "@stonewall",
      "@graineye",
      "@culvert.frame",
      "@rockface",
      "@tidegate",
      "@iceroad.icp",
      "@ferryramp",
      "@canallock",
      "@concretewall",
      "@landfill.edge",
      "@watermain",
      "@cablecar.vis",
      "@overpass.icp",
      "@freshstudio",
    ];
    return {
      id: `ds${idx}`,
      title: titles[i],
      creator: creators[i],
      coverImageUrl: COVER_IMAGES[i % COVER_IMAGES.length],
      description: "A quiet Mint Moment set with minimal activity so far.",
      totalPacks: 40 + (i % 4) * 10,
      remainingPacks: 35 + (i % 5) * 2,
      pricePerPack: 3.0 + (i % 4) * 0.5,
      totalVolume: Math.max(0, 4 - Math.floor(i / 10)),
      salesCount: 0,
      nftTrades: 0,
      uniqueCollectors: Math.max(0, 2 - Math.floor(i / 15)),
      listedAt: i < 4 ? hoursAgoMs(i + 1) : daysAgoMs(700 + i * 12),
      recentSales: [],
      packOpens: Math.max(0, 5 - Math.floor(i / 6)),
      previewPlays: Math.max(0, 20 - i),
      previewReplays: Math.max(0, 5 - Math.floor(i / 6)),
      tapExpansions: Math.max(0, 8 - Math.floor(i / 4)),
      videoCompletionRate: Math.max(0.1, 0.4 - i * 0.012),
      recentActivityVelocity: i < 4 ? 2 : 0,
      trendingTag: false,
    } satisfies MintMomentSetRank;
  }),
];

const TIME_RANGE_MS: Record<string, number> = {
  "24H": 24 * 60 * 60 * 1000,
  "7D": 7 * 24 * 60 * 60 * 1000,
  "30D": 30 * 24 * 60 * 60 * 1000,
};

export function getDiscoverSets(
  timeRange: "ALL_TIME" | "24H" | "7D" | "30D",
): MintMomentSetRank[] {
  const nowMs = Date.now();
  const cutoff =
    timeRange === "ALL_TIME"
      ? null
      : new Date(nowMs - TIME_RANGE_MS[timeRange]);

  const filtered = cutoff
    ? MOCK_DISCOVER_SETS.filter((s) => s.listedAt >= cutoff.getTime())
    : MOCK_DISCOVER_SETS;

  return [...filtered]
    .sort(
      (a, b) =>
        computeEngagementScore(b, nowMs) - computeEngagementScore(a, nowMs),
    )
    .slice(0, 100);
}

export interface DiscoverSections {
  trendingNow: MintMomentSetRank[];
  mostOpened: MintMomentSetRank[];
  risingFast: MintMomentSetRank[];
  mostCollected: MintMomentSetRank[];
  freshMoments: MintMomentSetRank[];
}

export function getDiscoverSections(
  timeRange: "ALL_TIME" | "24H" | "7D" | "30D",
): DiscoverSections {
  const nowMs = Date.now();
  const cutoff =
    timeRange === "ALL_TIME"
      ? null
      : new Date(nowMs - TIME_RANGE_MS[timeRange]);

  const pool = cutoff
    ? MOCK_DISCOVER_SETS.filter((s) => s.listedAt >= cutoff.getTime())
    : MOCK_DISCOVER_SETS;

  const scored = [...pool].sort(
    (a, b) =>
      computeEngagementScore(b, nowMs) - computeEngagementScore(a, nowMs),
  );

  const h72 = nowMs - 72 * 3600000;

  const trendingNow = scored.slice(0, 6);

  const mostOpened = [...pool]
    .sort((a, b) => b.packOpens - a.packOpens)
    .slice(0, 6);

  const risingFast = [...pool]
    .sort((a, b) => {
      const aScore =
        a.recentActivityVelocity * 2 + (a.listedAt >= h72 ? 50 : 0);
      const bScore =
        b.recentActivityVelocity * 2 + (b.listedAt >= h72 ? 50 : 0);
      return bScore - aScore;
    })
    .slice(0, 6);

  const mostCollected = [...pool]
    .sort((a, b) => b.uniqueCollectors - a.uniqueCollectors)
    .slice(0, 6);

  const freshMoments = [...pool]
    .sort((a, b) => b.listedAt - a.listedAt)
    .slice(0, 6);

  return { trendingNow, mostOpened, risingFast, mostCollected, freshMoments };
}
