export interface MintMomentSetRank {
  id: string;
  title: string;
  creator: string;
  coverImageUrl: string;
  previewClipUrl?: string;
  description: string;
  totalPacks: number;
  remainingPacks: number;
  pricePerPack: number;
  totalVolume: number;
  salesCount: number;
  nftTrades: number;
  uniqueCollectors: number;
  listedAt: number;
  recentSales: { itemTitle: string; priceUsd: number; timeAgo: string }[];
}

// Weighted scoring:
// score = (totalVolume * 0.40) + (salesCount * 8 * 0.25) + (nftTrades * 6 * 0.15) + (uniqueCollectors * 10 * 0.15) + (recentBoost * 0.05)
export function computeScore(
  set: MintMomentSetRank,
  nowMs: number = Date.now(),
): number {
  const ageMs = nowMs - set.listedAt;
  const ageH = ageMs / (1000 * 60 * 60);
  const recentBoost = ageH <= 24 ? 1000 : Math.max(0, 1000 - ageH * 3);

  return (
    set.totalVolume * 0.4 +
    set.salesCount * 8 * 0.25 +
    set.nftTrades * 6 * 0.15 +
    set.uniqueCollectors * 10 * 0.15 +
    recentBoost * 0.05
  );
}

const COVER_IMAGES = [
  "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&q=80",
  "https://images.unsplash.com/photo-1492551557933-34265f7af79e?w=400&q=80",
  "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=400&q=80",
  "https://images.unsplash.com/photo-1504274066651-8d31a536b11a?w=400&q=80",
  "https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=400&q=80",
  "https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?w=400&q=80",
  "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=400&q=80",
  "https://images.unsplash.com/photo-1433360405326-e50f909805b3?w=400&q=80",
];

const now = Date.now();
const h = 3600000;
const d = 86400000;

function hoursAgoMs(n: number) {
  return now - n * h;
}
function daysAgoMs(n: number) {
  return now - n * d;
}

export const MOCK_DISCOVER_SETS: MintMomentSetRank[] = [
  {
    id: "ds001",
    title: "Morning Coffee",
    creator: "@erin",
    coverImageUrl: COVER_IMAGES[0],
    description:
      "A quiet morning ritual captured in 9 stills and one 30-second film. The scent of espresso in soft winter light.",
    totalPacks: 100,
    remainingPacks: 8,
    pricePerPack: 3.5,
    totalVolume: 1834,
    salesCount: 312,
    nftTrades: 87,
    uniqueCollectors: 74,
    listedAt: daysAgoMs(45),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "2h ago" },
      { itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "5h ago" },
      { itemTitle: "NFT trade", priceUsd: 18, timeAgo: "1d ago" },
    ],
  },
  {
    id: "ds002",
    title: "Sunset Ride",
    creator: "@coastaldrift",
    coverImageUrl: COVER_IMAGES[1],
    description:
      "Long coastal highway, golden hour from the saddle. 9 frames of pure motion.",
    totalPacks: 80,
    remainingPacks: 12,
    pricePerPack: 4.0,
    totalVolume: 1640,
    salesCount: 280,
    nftTrades: 74,
    uniqueCollectors: 63,
    listedAt: daysAgoMs(38),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "3h ago" },
      { itemTitle: "NFT trade", priceUsd: 22, timeAgo: "8h ago" },
    ],
  },
  {
    id: "ds003",
    title: "Golden Hour",
    creator: "@lightchaser",
    coverImageUrl: COVER_IMAGES[4],
    description:
      "That 40-minute window before dusk where everything turns amber. Chased across three cities.",
    totalPacks: 120,
    remainingPacks: 5,
    pricePerPack: 3.0,
    totalVolume: 1560,
    salesCount: 340,
    nftTrades: 91,
    uniqueCollectors: 82,
    listedAt: daysAgoMs(60),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 3.0, timeAgo: "1h ago" },
      { itemTitle: "Pack sold", priceUsd: 3.0, timeAgo: "4h ago" },
      { itemTitle: "NFT trade", priceUsd: 14, timeAgo: "12h ago" },
    ],
  },
  {
    id: "ds004",
    title: "Late Night Drive",
    creator: "neon_rider.icp",
    coverImageUrl: COVER_IMAGES[1],
    description:
      "City after midnight — sodium lights, empty boulevards, the hum of the engine.",
    totalPacks: 75,
    remainingPacks: 0,
    pricePerPack: 5.0,
    totalVolume: 1420,
    salesCount: 218,
    nftTrades: 66,
    uniqueCollectors: 55,
    listedAt: daysAgoMs(30),
    recentSales: [
      { itemTitle: "NFT trade", priceUsd: 28, timeAgo: "6h ago" },
      { itemTitle: "NFT trade", priceUsd: 19, timeAgo: "1d ago" },
    ],
  },
  {
    id: "ds005",
    title: "Ocean Mist",
    creator: "@wavecatcher",
    coverImageUrl: COVER_IMAGES[2],
    description:
      "Pre-dawn at the shore. Cold sand, salt air, and waves that never stop coming.",
    totalPacks: 90,
    remainingPacks: 22,
    pricePerPack: 3.5,
    totalVolume: 1204,
    salesCount: 198,
    nftTrades: 54,
    uniqueCollectors: 47,
    listedAt: daysAgoMs(20),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "30m ago" },
      { itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "2h ago" },
    ],
  },
  {
    id: "ds006",
    title: "City Lights",
    creator: "@urbanmoment",
    coverImageUrl: COVER_IMAGES[1],
    description:
      "An upward gaze through glass towers and rain-slicked streets.",
    totalPacks: 60,
    remainingPacks: 14,
    pricePerPack: 4.5,
    totalVolume: 1140,
    salesCount: 176,
    nftTrades: 48,
    uniqueCollectors: 41,
    listedAt: hoursAgoMs(18),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 4.5, timeAgo: "45m ago" },
      { itemTitle: "Pack sold", priceUsd: 4.5, timeAgo: "3h ago" },
      { itemTitle: "NFT trade", priceUsd: 32, timeAgo: "5h ago" },
    ],
  },
  {
    id: "ds007",
    title: "First Snow",
    creator: "@winterstudio",
    coverImageUrl: COVER_IMAGES[6],
    description:
      "The day everything goes quiet. First snowfall of the season, documented minute by minute.",
    totalPacks: 110,
    remainingPacks: 31,
    pricePerPack: 3.0,
    totalVolume: 1080,
    salesCount: 204,
    nftTrades: 61,
    uniqueCollectors: 58,
    listedAt: daysAgoMs(14),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 3.0, timeAgo: "1h ago" },
      { itemTitle: "Pack sold", priceUsd: 3.0, timeAgo: "6h ago" },
    ],
  },
  {
    id: "ds008",
    title: "Bloom",
    creator: "@gardenpath",
    coverImageUrl: COVER_IMAGES[5],
    description:
      "Spring arrives in a single garden over three weeks. Macro stills of petals breaking open.",
    totalPacks: 85,
    remainingPacks: 18,
    pricePerPack: 3.5,
    totalVolume: 960,
    salesCount: 167,
    nftTrades: 43,
    uniqueCollectors: 39,
    listedAt: daysAgoMs(25),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "2h ago" },
      { itemTitle: "NFT trade", priceUsd: 16, timeAgo: "1d ago" },
    ],
  },
  {
    id: "ds009",
    title: "Mountain Top",
    creator: "@altitudelab",
    coverImageUrl: COVER_IMAGES[0],
    description:
      "Summit series: nine peaks, nine Moments. The thin air makes everything sharper.",
    totalPacks: 70,
    remainingPacks: 9,
    pricePerPack: 5.0,
    totalVolume: 940,
    salesCount: 142,
    nftTrades: 37,
    uniqueCollectors: 33,
    listedAt: daysAgoMs(50),
    recentSales: [
      { itemTitle: "NFT trade", priceUsd: 24, timeAgo: "4h ago" },
      { itemTitle: "Pack sold", priceUsd: 5.0, timeAgo: "10h ago" },
    ],
  },
  {
    id: "ds010",
    title: "Midnight Run",
    creator: "@runnersguild",
    coverImageUrl: COVER_IMAGES[6],
    description:
      "Running through the city at 2am. Breath visible. Pavement slick. Pure focus.",
    totalPacks: 65,
    remainingPacks: 11,
    pricePerPack: 4.0,
    totalVolume: 876,
    salesCount: 138,
    nftTrades: 35,
    uniqueCollectors: 30,
    listedAt: daysAgoMs(18),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "1h ago" },
      { itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "7h ago" },
    ],
  },
  {
    id: "ds011",
    title: "Foggy Morning",
    creator: "@mist.frames",
    coverImageUrl: COVER_IMAGES[2],
    description: "When the valley fills with fog before the sun burns it away.",
    totalPacks: 80,
    remainingPacks: 26,
    pricePerPack: 3.0,
    totalVolume: 800,
    salesCount: 128,
    nftTrades: 29,
    uniqueCollectors: 27,
    listedAt: daysAgoMs(22),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 3.0, timeAgo: "3h ago" }],
  },
  {
    id: "ds012",
    title: "Desert Bloom",
    creator: "@aridstudio",
    coverImageUrl: COVER_IMAGES[4],
    description: "After the rain, the desert comes alive for 72 hours.",
    totalPacks: 60,
    remainingPacks: 19,
    pricePerPack: 4.5,
    totalVolume: 756,
    salesCount: 112,
    nftTrades: 31,
    uniqueCollectors: 28,
    listedAt: daysAgoMs(35),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 4.5, timeAgo: "5h ago" }],
  },
  {
    id: "ds013",
    title: "Tokyo Alley",
    creator: "@streetframe.jp",
    coverImageUrl: COVER_IMAGES[1],
    description: "A single alley in Shinjuku at 11pm. Neon vs. rain.",
    totalPacks: 50,
    remainingPacks: 7,
    pricePerPack: 6.0,
    totalVolume: 748,
    salesCount: 96,
    nftTrades: 42,
    uniqueCollectors: 36,
    listedAt: daysAgoMs(28),
    recentSales: [
      { itemTitle: "NFT trade", priceUsd: 38, timeAgo: "2h ago" },
      { itemTitle: "Pack sold", priceUsd: 6.0, timeAgo: "9h ago" },
    ],
  },
  {
    id: "ds014",
    title: "Harvest Light",
    creator: "@fieldsong",
    coverImageUrl: COVER_IMAGES[4],
    description:
      "October fields, amber skies, and the last warmth before the freeze.",
    totalPacks: 90,
    remainingPacks: 34,
    pricePerPack: 3.5,
    totalVolume: 710,
    salesCount: 118,
    nftTrades: 27,
    uniqueCollectors: 25,
    listedAt: daysAgoMs(40),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "6h ago" }],
  },
  {
    id: "ds015",
    title: "Rain Window",
    creator: "@quietframe",
    coverImageUrl: COVER_IMAGES[3],
    description:
      "Watching the city through a rain-streaked window from the inside.",
    totalPacks: 55,
    remainingPacks: 20,
    pricePerPack: 4.0,
    totalVolume: 680,
    salesCount: 104,
    nftTrades: 24,
    uniqueCollectors: 22,
    listedAt: hoursAgoMs(6),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "20m ago" },
      { itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "1h ago" },
    ],
  },
  {
    id: "ds016",
    title: "Sunday Market",
    creator: "@marketlight",
    coverImageUrl: COVER_IMAGES[5],
    description: "Farmers market, 8am. Color, texture, community.",
    totalPacks: 75,
    remainingPacks: 28,
    pricePerPack: 3.0,
    totalVolume: 634,
    salesCount: 98,
    nftTrades: 21,
    uniqueCollectors: 20,
    listedAt: daysAgoMs(12),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 3.0, timeAgo: "4h ago" }],
  },
  {
    id: "ds017",
    title: "Rooftop Session",
    creator: "@skylineview",
    coverImageUrl: COVER_IMAGES[1],
    description: "Music on a downtown rooftop as the city lights come on.",
    totalPacks: 45,
    remainingPacks: 15,
    pricePerPack: 5.0,
    totalVolume: 612,
    salesCount: 84,
    nftTrades: 32,
    uniqueCollectors: 29,
    listedAt: daysAgoMs(16),
    recentSales: [{ itemTitle: "NFT trade", priceUsd: 27, timeAgo: "3h ago" }],
  },
  {
    id: "ds018",
    title: "Tide Pool",
    creator: "@tidewatcher",
    coverImageUrl: COVER_IMAGES[2],
    description:
      "Miniature ecosystems revealed at low tide. Nine frames, nine worlds.",
    totalPacks: 65,
    remainingPacks: 23,
    pricePerPack: 4.0,
    totalVolume: 580,
    salesCount: 88,
    nftTrades: 19,
    uniqueCollectors: 18,
    listedAt: daysAgoMs(33),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "8h ago" }],
  },
  {
    id: "ds019",
    title: "Industrial Dusk",
    creator: "@ironframe",
    coverImageUrl: COVER_IMAGES[7],
    description: "Factory district at dusk. Steam, rust, and fading light.",
    totalPacks: 50,
    remainingPacks: 17,
    pricePerPack: 4.5,
    totalVolume: 560,
    salesCount: 78,
    nftTrades: 26,
    uniqueCollectors: 24,
    listedAt: daysAgoMs(21),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 4.5, timeAgo: "7h ago" }],
  },
  {
    id: "ds020",
    title: "Night Forest",
    creator: "@treeline",
    coverImageUrl: COVER_IMAGES[7],
    description:
      "Old growth forest at 3am. Bioluminescence and ancient silence.",
    totalPacks: 70,
    remainingPacks: 30,
    pricePerPack: 3.5,
    totalVolume: 540,
    salesCount: 82,
    nftTrades: 22,
    uniqueCollectors: 21,
    listedAt: daysAgoMs(27),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "5h ago" }],
  },
  // Sets 21-40
  {
    id: "ds021",
    title: "Cobblestone",
    creator: "@oldcity.frame",
    coverImageUrl: COVER_IMAGES[3],
    description:
      "Ancient streets of a medieval quarter. Centuries layered in stone.",
    totalPacks: 60,
    remainingPacks: 22,
    pricePerPack: 4.0,
    totalVolume: 510,
    salesCount: 74,
    nftTrades: 18,
    uniqueCollectors: 17,
    listedAt: daysAgoMs(44),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "6h ago" }],
  },
  {
    id: "ds022",
    title: "Fire Season",
    creator: "@ashframe",
    coverImageUrl: COVER_IMAGES[4],
    description:
      "California hills in late summer — amber, smoke, and survival.",
    totalPacks: 55,
    remainingPacks: 16,
    pricePerPack: 5.0,
    totalVolume: 498,
    salesCount: 68,
    nftTrades: 24,
    uniqueCollectors: 23,
    listedAt: daysAgoMs(52),
    recentSales: [{ itemTitle: "NFT trade", priceUsd: 31, timeAgo: "1d ago" }],
  },
  {
    id: "ds023",
    title: "Greenhouse",
    creator: "@heatframe",
    coverImageUrl: COVER_IMAGES[5],
    description:
      "An artist's greenhouse — glass walls, tropical chaos, perfect light.",
    totalPacks: 65,
    remainingPacks: 25,
    pricePerPack: 3.5,
    totalVolume: 474,
    salesCount: 72,
    nftTrades: 17,
    uniqueCollectors: 16,
    listedAt: daysAgoMs(19),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "3h ago" }],
  },
  {
    id: "ds024",
    title: "Salt Flat",
    creator: "@horizonrider",
    coverImageUrl: COVER_IMAGES[0],
    description:
      "Bonneville at dawn. The world's largest mirror. Nothing for miles.",
    totalPacks: 40,
    remainingPacks: 8,
    pricePerPack: 6.0,
    totalVolume: 462,
    salesCount: 56,
    nftTrades: 28,
    uniqueCollectors: 26,
    listedAt: daysAgoMs(36),
    recentSales: [{ itemTitle: "NFT trade", priceUsd: 42, timeAgo: "2d ago" }],
  },
  {
    id: "ds025",
    title: "Ferry Crossing",
    creator: "@seacommute",
    coverImageUrl: COVER_IMAGES[2],
    description:
      "The 7am ferry. Regular people, extraordinary light, 30 minutes of suspension.",
    totalPacks: 70,
    remainingPacks: 33,
    pricePerPack: 3.5,
    totalVolume: 440,
    salesCount: 66,
    nftTrades: 15,
    uniqueCollectors: 14,
    listedAt: daysAgoMs(29),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "4h ago" }],
  },
  {
    id: "ds026",
    title: "Skate Plaza",
    creator: "@concrete.poet",
    coverImageUrl: COVER_IMAGES[1],
    description:
      "The municipal plaza reclaimed. Wheels on marble at golden hour.",
    totalPacks: 55,
    remainingPacks: 19,
    pricePerPack: 4.0,
    totalVolume: 420,
    salesCount: 62,
    nftTrades: 20,
    uniqueCollectors: 19,
    listedAt: hoursAgoMs(14),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "1h ago" }],
  },
  {
    id: "ds027",
    title: "Cathedral Glass",
    creator: "@lightarchitect",
    coverImageUrl: COVER_IMAGES[4],
    description: "Stained glass at peak noon. Color, transcendence, geometry.",
    totalPacks: 45,
    remainingPacks: 11,
    pricePerPack: 5.0,
    totalVolume: 408,
    salesCount: 58,
    nftTrades: 19,
    uniqueCollectors: 18,
    listedAt: daysAgoMs(48),
    recentSales: [{ itemTitle: "NFT trade", priceUsd: 25, timeAgo: "2d ago" }],
  },
  {
    id: "ds028",
    title: "Bakery Open",
    creator: "@dawnbake",
    coverImageUrl: COVER_IMAGES[5],
    description:
      "4:30am. The first loaves go in. A bakery coming alive in the dark.",
    totalPacks: 80,
    remainingPacks: 42,
    pricePerPack: 3.0,
    totalVolume: 390,
    salesCount: 60,
    nftTrades: 13,
    uniqueCollectors: 12,
    listedAt: daysAgoMs(31),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 3.0, timeAgo: "5h ago" }],
  },
  {
    id: "ds029",
    title: "Fisherman's Wharf",
    creator: "@portframe",
    coverImageUrl: COVER_IMAGES[2],
    description:
      "Working waterfront, 5am. Ice, motion, and the smell of the sea.",
    totalPacks: 60,
    remainingPacks: 27,
    pricePerPack: 4.0,
    totalVolume: 372,
    salesCount: 54,
    nftTrades: 14,
    uniqueCollectors: 13,
    listedAt: daysAgoMs(43),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "7h ago" }],
  },
  {
    id: "ds030",
    title: "Transit Hour",
    creator: "@metro.visual",
    coverImageUrl: COVER_IMAGES[1],
    description:
      "The subway at rush hour. Humanity compressed into beautiful chaos.",
    totalPacks: 75,
    remainingPacks: 38,
    pricePerPack: 3.5,
    totalVolume: 356,
    salesCount: 52,
    nftTrades: 12,
    uniqueCollectors: 11,
    listedAt: daysAgoMs(55),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "1d ago" }],
  },
  {
    id: "ds031",
    title: "Lavender Field",
    creator: "@provencal",
    coverImageUrl: COVER_IMAGES[5],
    description:
      "Provence in July. Purple horizon, bee drone, therapeutic stillness.",
    totalPacks: 90,
    remainingPacks: 48,
    pricePerPack: 3.0,
    totalVolume: 340,
    salesCount: 50,
    nftTrades: 11,
    uniqueCollectors: 10,
    listedAt: daysAgoMs(62),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 3.0, timeAgo: "2d ago" }],
  },
  {
    id: "ds032",
    title: "Boxing Gym",
    creator: "@sweatstudio",
    coverImageUrl: COVER_IMAGES[3],
    description:
      "Old gym, old school. Leather, sweat, and the smell of liniment.",
    totalPacks: 50,
    remainingPacks: 21,
    pricePerPack: 4.5,
    totalVolume: 328,
    salesCount: 46,
    nftTrades: 15,
    uniqueCollectors: 14,
    listedAt: daysAgoMs(39),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 4.5, timeAgo: "3h ago" }],
  },
  {
    id: "ds033",
    title: "Radio Tower",
    creator: "@frequencylab",
    coverImageUrl: COVER_IMAGES[6],
    description:
      "The tower that has been broadcasting for 50 years. Signal, structure, atmosphere.",
    totalPacks: 45,
    remainingPacks: 18,
    pricePerPack: 5.0,
    totalVolume: 316,
    salesCount: 42,
    nftTrades: 16,
    uniqueCollectors: 15,
    listedAt: daysAgoMs(47),
    recentSales: [{ itemTitle: "NFT trade", priceUsd: 29, timeAgo: "1d ago" }],
  },
  {
    id: "ds034",
    title: "Street Food Night",
    creator: "@nightmarketframe",
    coverImageUrl: COVER_IMAGES[1],
    description:
      "Bangkok night market. Steam, smoke, neon, and a thousand small fires.",
    totalPacks: 65,
    remainingPacks: 30,
    pricePerPack: 3.5,
    totalVolume: 302,
    salesCount: 44,
    nftTrades: 10,
    uniqueCollectors: 9,
    listedAt: daysAgoMs(51),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "8h ago" }],
  },
  {
    id: "ds035",
    title: "Cellar Door",
    creator: "@vineyardvault",
    coverImageUrl: COVER_IMAGES[7],
    description:
      "Burgundy wine cellar. Barrels, cork, and centuries of patience.",
    totalPacks: 40,
    remainingPacks: 13,
    pricePerPack: 6.0,
    totalVolume: 294,
    salesCount: 36,
    nftTrades: 18,
    uniqueCollectors: 17,
    listedAt: daysAgoMs(70),
    recentSales: [{ itemTitle: "NFT trade", priceUsd: 44, timeAgo: "3d ago" }],
  },
  {
    id: "ds036",
    title: "Anchor Hold",
    creator: "@deepport",
    coverImageUrl: COVER_IMAGES[2],
    description:
      "Container port, Tuesday. Scale, order, and the weight of global trade.",
    totalPacks: 60,
    remainingPacks: 26,
    pricePerPack: 4.0,
    totalVolume: 280,
    salesCount: 40,
    nftTrades: 9,
    uniqueCollectors: 9,
    listedAt: daysAgoMs(58),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "2d ago" }],
  },
  {
    id: "ds037",
    title: "Velvet Dark",
    creator: "@luxframe",
    coverImageUrl: COVER_IMAGES[6],
    description:
      "Nightclub at 1am through a 28mm. People, texture, the edge of restraint.",
    totalPacks: 50,
    remainingPacks: 22,
    pricePerPack: 4.5,
    totalVolume: 268,
    salesCount: 38,
    nftTrades: 12,
    uniqueCollectors: 11,
    listedAt: daysAgoMs(63),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 4.5, timeAgo: "1d ago" }],
  },
  {
    id: "ds038",
    title: "Courtyard Noon",
    creator: "@plazashot",
    coverImageUrl: COVER_IMAGES[4],
    description:
      "Moorish courtyard at noon. Shadow geometry, tile patterns, brutal light.",
    totalPacks: 70,
    remainingPacks: 34,
    pricePerPack: 3.5,
    totalVolume: 256,
    salesCount: 36,
    nftTrades: 8,
    uniqueCollectors: 8,
    listedAt: daysAgoMs(80),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "3d ago" }],
  },
  {
    id: "ds039",
    title: "Ice Rink",
    creator: "@coldframe",
    coverImageUrl: COVER_IMAGES[2],
    description:
      "Old municipal ice rink. Blades on ice, breath clouds, the smell of Zamboni.",
    totalPacks: 55,
    remainingPacks: 23,
    pricePerPack: 4.0,
    totalVolume: 244,
    salesCount: 34,
    nftTrades: 9,
    uniqueCollectors: 8,
    listedAt: daysAgoMs(41),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "2d ago" }],
  },
  {
    id: "ds040",
    title: "Prairie Sky",
    creator: "@flatlandview",
    coverImageUrl: COVER_IMAGES[0],
    description:
      "500 miles of nothing but sky. The Great Plains from a truck window.",
    totalPacks: 80,
    remainingPacks: 45,
    pricePerPack: 3.0,
    totalVolume: 232,
    salesCount: 32,
    nftTrades: 7,
    uniqueCollectors: 7,
    listedAt: daysAgoMs(95),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 3.0, timeAgo: "4d ago" }],
  },
  // Sets 41-60
  {
    id: "ds041",
    title: "Backstreet Chapel",
    creator: "@sacredframe",
    coverImageUrl: COVER_IMAGES[7],
    description:
      "Small chapel in a back alley. Sunday service, 8 members, pure devotion.",
    totalPacks: 45,
    remainingPacks: 18,
    pricePerPack: 4.5,
    totalVolume: 220,
    salesCount: 30,
    nftTrades: 8,
    uniqueCollectors: 7,
    listedAt: daysAgoMs(72),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 4.5, timeAgo: "3d ago" }],
  },
  {
    id: "ds042",
    title: "Fishing Village",
    creator: "@coastallife",
    coverImageUrl: COVER_IMAGES[2],
    description:
      "Portuguese fishing village, Wednesday morning. Nets, boats, the rhythm of the sea.",
    totalPacks: 60,
    remainingPacks: 27,
    pricePerPack: 4.0,
    totalVolume: 210,
    salesCount: 28,
    nftTrades: 7,
    uniqueCollectors: 7,
    listedAt: daysAgoMs(88),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "5d ago" }],
  },
  {
    id: "ds043",
    title: "Dawn Swimmer",
    creator: "@poolframe",
    coverImageUrl: COVER_IMAGES[2],
    description:
      "Olympic pool, 5:30am. Lap swimmer, lane lines, chlorine blue.",
    totalPacks: 50,
    remainingPacks: 21,
    pricePerPack: 4.0,
    totalVolume: 200,
    salesCount: 26,
    nftTrades: 7,
    uniqueCollectors: 6,
    listedAt: daysAgoMs(56),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "2d ago" }],
  },
  {
    id: "ds044",
    title: "Concrete Wave",
    creator: "@surf.doc",
    coverImageUrl: COVER_IMAGES[2],
    description:
      "Surfing a river wave in the middle of a city. Pure urban contradiction.",
    totalPacks: 45,
    remainingPacks: 16,
    pricePerPack: 4.5,
    totalVolume: 192,
    salesCount: 24,
    nftTrades: 9,
    uniqueCollectors: 8,
    listedAt: daysAgoMs(67),
    recentSales: [{ itemTitle: "NFT trade", priceUsd: 21, timeAgo: "3d ago" }],
  },
  {
    id: "ds045",
    title: "Loom Room",
    creator: "@textileframe",
    coverImageUrl: COVER_IMAGES[5],
    description:
      "Traditional weaving studio. Thread, pattern, and the physics of cloth.",
    totalPacks: 70,
    remainingPacks: 38,
    pricePerPack: 3.5,
    totalVolume: 182,
    salesCount: 22,
    nftTrades: 6,
    uniqueCollectors: 6,
    listedAt: daysAgoMs(105),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "6d ago" }],
  },
  {
    id: "ds046",
    title: "Tower Crane",
    creator: "@constructframe",
    coverImageUrl: COVER_IMAGES[3],
    description:
      "Operating a tower crane 200m up. The city at work, from above.",
    totalPacks: 40,
    remainingPacks: 14,
    pricePerPack: 5.0,
    totalVolume: 174,
    salesCount: 20,
    nftTrades: 8,
    uniqueCollectors: 7,
    listedAt: daysAgoMs(92),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 5.0, timeAgo: "4d ago" }],
  },
  {
    id: "ds047",
    title: "Record Store",
    creator: "@vinyldog",
    coverImageUrl: COVER_IMAGES[3],
    description:
      "Last surviving record store in the neighborhood. Bins, dust, devotion.",
    totalPacks: 55,
    remainingPacks: 28,
    pricePerPack: 4.0,
    totalVolume: 166,
    salesCount: 18,
    nftTrades: 6,
    uniqueCollectors: 6,
    listedAt: daysAgoMs(76),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "5d ago" }],
  },
  {
    id: "ds048",
    title: "Pottery Wheel",
    creator: "@claywork",
    coverImageUrl: COVER_IMAGES[5],
    description:
      "An afternoon in a ceramics studio. Hands in clay, the hum of the wheel.",
    totalPacks: 60,
    remainingPacks: 32,
    pricePerPack: 3.5,
    totalVolume: 158,
    salesCount: 16,
    nftTrades: 5,
    uniqueCollectors: 5,
    listedAt: daysAgoMs(119),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "1w ago" }],
  },
  {
    id: "ds049",
    title: "Harbour Seal",
    creator: "@wildframe",
    coverImageUrl: COVER_IMAGES[2],
    description:
      "Harbour seals hauled out on a dock. Bureaucratic chaos meets natural grace.",
    totalPacks: 45,
    remainingPacks: 19,
    pricePerPack: 4.5,
    totalVolume: 150,
    salesCount: 14,
    nftTrades: 7,
    uniqueCollectors: 6,
    listedAt: daysAgoMs(83),
    recentSales: [{ itemTitle: "NFT trade", priceUsd: 18, timeAgo: "4d ago" }],
  },
  {
    id: "ds050",
    title: "Midnight Diner",
    creator: "@dinerframe",
    coverImageUrl: COVER_IMAGES[1],
    description:
      "24-hour diner at 3am. Regulars, coffee, the fluorescent loneliness of it.",
    totalPacks: 50,
    remainingPacks: 24,
    pricePerPack: 4.0,
    totalVolume: 144,
    salesCount: 13,
    nftTrades: 5,
    uniqueCollectors: 5,
    listedAt: daysAgoMs(134),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "1w ago" }],
  },
  {
    id: "ds051",
    title: "Cypress Alley",
    creator: "@tuscanlight",
    coverImageUrl: COVER_IMAGES[7],
    description: "A cypress-lined road in Tuscany at first light.",
    totalPacks: 65,
    remainingPacks: 36,
    pricePerPack: 3.5,
    totalVolume: 136,
    salesCount: 12,
    nftTrades: 4,
    uniqueCollectors: 4,
    listedAt: daysAgoMs(148),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "1w ago" }],
  },
  {
    id: "ds052",
    title: "Steelwork",
    creator: "@foundry.frame",
    coverImageUrl: COVER_IMAGES[3],
    description: "Inside an active foundry. Metal, heat, and human precision.",
    totalPacks: 40,
    remainingPacks: 17,
    pricePerPack: 5.0,
    totalVolume: 128,
    salesCount: 11,
    nftTrades: 5,
    uniqueCollectors: 4,
    listedAt: daysAgoMs(160),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 5.0, timeAgo: "10d ago" },
    ],
  },
  {
    id: "ds053",
    title: "Coral Garden",
    creator: "@reefwatch",
    coverImageUrl: COVER_IMAGES[2],
    description:
      "Shallow water coral garden, Raja Ampat. Nine frames, one breath hold each.",
    totalPacks: 55,
    remainingPacks: 28,
    pricePerPack: 4.5,
    totalVolume: 120,
    salesCount: 10,
    nftTrades: 5,
    uniqueCollectors: 4,
    listedAt: daysAgoMs(175),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 4.5, timeAgo: "2w ago" }],
  },
  {
    id: "ds054",
    title: "Chess Club",
    creator: "@checkmate.frame",
    coverImageUrl: COVER_IMAGES[3],
    description:
      "Saturday tournament, local chess club. 40 boards, 80 people, one clock ticking.",
    totalPacks: 70,
    remainingPacks: 42,
    pricePerPack: 3.0,
    totalVolume: 112,
    salesCount: 10,
    nftTrades: 3,
    uniqueCollectors: 3,
    listedAt: daysAgoMs(200),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 3.0, timeAgo: "2w ago" }],
  },
  {
    id: "ds055",
    title: "Highway 1",
    creator: "@coastalroute",
    coverImageUrl: COVER_IMAGES[0],
    description:
      "Driving Highway 1 at dawn. Cliffs, fog, the edge of the continent.",
    totalPacks: 50,
    remainingPacks: 26,
    pricePerPack: 4.0,
    totalVolume: 106,
    salesCount: 9,
    nftTrades: 3,
    uniqueCollectors: 3,
    listedAt: daysAgoMs(220),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "3w ago" }],
  },
  {
    id: "ds056",
    title: "Knife Sharpening",
    creator: "@edgecraft",
    coverImageUrl: COVER_IMAGES[3],
    description:
      "Old knife sharpener, Osaka market. Sparks, skill, the ritual of the blade.",
    totalPacks: 40,
    remainingPacks: 19,
    pricePerPack: 5.0,
    totalVolume: 100,
    salesCount: 8,
    nftTrades: 4,
    uniqueCollectors: 4,
    listedAt: daysAgoMs(240),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 5.0, timeAgo: "3w ago" }],
  },
  {
    id: "ds057",
    title: "Lake at Dusk",
    creator: "@lakestudio",
    coverImageUrl: COVER_IMAGES[6],
    description:
      "A quiet lake as the light dies. Nine frames of diminishing warmth.",
    totalPacks: 60,
    remainingPacks: 34,
    pricePerPack: 3.5,
    totalVolume: 94,
    salesCount: 8,
    nftTrades: 2,
    uniqueCollectors: 2,
    listedAt: daysAgoMs(260),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "4w ago" }],
  },
  {
    id: "ds058",
    title: "Orchid House",
    creator: "@botanica",
    coverImageUrl: COVER_IMAGES[5],
    description:
      "A private orchid collection — 400 varieties, one afternoon, natural light only.",
    totalPacks: 75,
    remainingPacks: 48,
    pricePerPack: 3.0,
    totalVolume: 88,
    salesCount: 8,
    nftTrades: 2,
    uniqueCollectors: 2,
    listedAt: daysAgoMs(280),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 3.0, timeAgo: "4w ago" }],
  },
  {
    id: "ds059",
    title: "Pigeon Racing",
    creator: "@homeward",
    coverImageUrl: COVER_IMAGES[0],
    description:
      "Pigeon racing club, Lancashire. Release day, hope in the air.",
    totalPacks: 45,
    remainingPacks: 25,
    pricePerPack: 4.0,
    totalVolume: 82,
    salesCount: 7,
    nftTrades: 2,
    uniqueCollectors: 2,
    listedAt: daysAgoMs(300),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "5w ago" }],
  },
  {
    id: "ds060",
    title: "Marble Quarry",
    creator: "@stoneframe",
    coverImageUrl: COVER_IMAGES[0],
    description:
      "Carrara quarry in morning light. White against white. Scale that humbles.",
    totalPacks: 50,
    remainingPacks: 30,
    pricePerPack: 4.5,
    totalVolume: 76,
    salesCount: 6,
    nftTrades: 2,
    uniqueCollectors: 2,
    listedAt: daysAgoMs(320),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 4.5, timeAgo: "6w ago" }],
  },
  // Sets 61-80
  {
    id: "ds061",
    title: "Autumn Train",
    creator: "@railframe",
    coverImageUrl: COVER_IMAGES[7],
    description:
      "Cross-country train, late October. Windows full of turning leaves.",
    totalPacks: 55,
    remainingPacks: 32,
    pricePerPack: 3.5,
    totalVolume: 70,
    salesCount: 6,
    nftTrades: 2,
    uniqueCollectors: 2,
    listedAt: daysAgoMs(340),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "7w ago" }],
  },
  {
    id: "ds062",
    title: "Jazz Late Set",
    creator: "@clubframe",
    coverImageUrl: COVER_IMAGES[1],
    description:
      "Last set of the night at a jazz club. Cigarette smoke and the horn.",
    totalPacks: 40,
    remainingPacks: 22,
    pricePerPack: 5.0,
    totalVolume: 65,
    salesCount: 5,
    nftTrades: 3,
    uniqueCollectors: 2,
    listedAt: daysAgoMs(355),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 5.0, timeAgo: "7w ago" }],
  },
  {
    id: "ds063",
    title: "Hot Springs",
    creator: "@geothermal",
    coverImageUrl: COVER_IMAGES[2],
    description: "Icelandic hot springs at -15°C. Steam, blue water, silence.",
    totalPacks: 60,
    remainingPacks: 38,
    pricePerPack: 4.0,
    totalVolume: 60,
    salesCount: 5,
    nftTrades: 2,
    uniqueCollectors: 2,
    listedAt: daysAgoMs(365),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "8w ago" }],
  },
  {
    id: "ds064",
    title: "Beekeeper",
    creator: "@hivemind",
    coverImageUrl: COVER_IMAGES[4],
    description:
      "A beekeeper at work — the hive, the smoke, the extraordinary calm.",
    totalPacks: 50,
    remainingPacks: 30,
    pricePerPack: 4.0,
    totalVolume: 56,
    salesCount: 5,
    nftTrades: 1,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(380),
    recentSales: [{ itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "9w ago" }],
  },
  {
    id: "ds065",
    title: "Bookbinder",
    creator: "@spinemaker",
    coverImageUrl: COVER_IMAGES[3],
    description:
      "Hand bookbinding, a craft older than printing. Leather, thread, and glue.",
    totalPacks: 45,
    remainingPacks: 28,
    pricePerPack: 4.5,
    totalVolume: 52,
    salesCount: 4,
    nftTrades: 2,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(400),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 4.5, timeAgo: "10w ago" },
    ],
  },
  {
    id: "ds066",
    title: "Night Crossing",
    creator: "@nightport",
    coverImageUrl: COVER_IMAGES[6],
    description:
      "Crossing the channel at night by ferry. Wake, stars, the dark water.",
    totalPacks: 55,
    remainingPacks: 34,
    pricePerPack: 3.5,
    totalVolume: 48,
    salesCount: 4,
    nftTrades: 1,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(415),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "10w ago" },
    ],
  },
  {
    id: "ds067",
    title: "Typewriter Row",
    creator: "@mechanicalframe",
    coverImageUrl: COVER_IMAGES[3],
    description:
      "A repair shop with 200 vintage typewriters. Keys, carriages, the clack.",
    totalPacks: 50,
    remainingPacks: 32,
    pricePerPack: 4.0,
    totalVolume: 44,
    salesCount: 4,
    nftTrades: 1,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(430),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "11w ago" },
    ],
  },
  {
    id: "ds068",
    title: "Harbour Glow",
    creator: "@portnight",
    coverImageUrl: COVER_IMAGES[2],
    description:
      "Harbour lights on still water. Reflections, silence, the smell of brine.",
    totalPacks: 65,
    remainingPacks: 44,
    pricePerPack: 3.5,
    totalVolume: 40,
    salesCount: 4,
    nftTrades: 1,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(445),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "11w ago" },
    ],
  },
  {
    id: "ds069",
    title: "Bell Tower",
    creator: "@campanile",
    coverImageUrl: COVER_IMAGES[4],
    description:
      "Inside a bell tower at noon. The sound before it becomes sound.",
    totalPacks: 40,
    remainingPacks: 24,
    pricePerPack: 5.0,
    totalVolume: 36,
    salesCount: 3,
    nftTrades: 1,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(460),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 5.0, timeAgo: "12w ago" },
    ],
  },
  {
    id: "ds070",
    title: "Grain Elevator",
    creator: "@siloframe",
    coverImageUrl: COVER_IMAGES[0],
    description:
      "Prairie grain elevator, September. The harvest economy in one structure.",
    totalPacks: 50,
    remainingPacks: 33,
    pricePerPack: 4.0,
    totalVolume: 32,
    salesCount: 3,
    nftTrades: 1,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(475),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "12w ago" },
    ],
  },
  {
    id: "ds071",
    title: "Antique Fair",
    creator: "@timecollector",
    coverImageUrl: COVER_IMAGES[3],
    description:
      "Annual antique fair. Objects without owners, waiting for the right eye.",
    totalPacks: 60,
    remainingPacks: 42,
    pricePerPack: 3.5,
    totalVolume: 28,
    salesCount: 3,
    nftTrades: 1,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(490),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "13w ago" },
    ],
  },
  {
    id: "ds072",
    title: "Tide Table",
    creator: "@lunarframe",
    coverImageUrl: COVER_IMAGES[2],
    description:
      "One beach over 24 hours of tidal cycle. Nine windows into time.",
    totalPacks: 45,
    remainingPacks: 30,
    pricePerPack: 4.0,
    totalVolume: 24,
    salesCount: 3,
    nftTrades: 1,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(505),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "14w ago" },
    ],
  },
  {
    id: "ds073",
    title: "Narrow Alley",
    creator: "@vertiframe",
    coverImageUrl: COVER_IMAGES[1],
    description:
      "A 90cm-wide alley in Fes medina. Two thousand years of foot traffic.",
    totalPacks: 50,
    remainingPacks: 34,
    pricePerPack: 4.5,
    totalVolume: 22,
    salesCount: 2,
    nftTrades: 1,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(520),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 4.5, timeAgo: "15w ago" },
    ],
  },
  {
    id: "ds074",
    title: "Window Box",
    creator: "@microframe",
    coverImageUrl: COVER_IMAGES[5],
    description:
      "Nine window boxes in an Amsterdam canal house. Seasons in miniature.",
    totalPacks: 60,
    remainingPacks: 42,
    pricePerPack: 3.5,
    totalVolume: 20,
    salesCount: 2,
    nftTrades: 0,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(535),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "16w ago" },
    ],
  },
  {
    id: "ds075",
    title: "Afternoon Nap",
    creator: "@quietroom",
    coverImageUrl: COVER_IMAGES[4],
    description:
      "The particular quality of Sunday afternoon light in a still apartment.",
    totalPacks: 40,
    remainingPacks: 26,
    pricePerPack: 4.0,
    totalVolume: 18,
    salesCount: 2,
    nftTrades: 0,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(550),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "17w ago" },
    ],
  },
  // Sets 76-100
  {
    id: "ds076",
    title: "Canal Lock",
    creator: "@canalframe",
    coverImageUrl: COVER_IMAGES[2],
    description:
      "A narrowboat navigating a canal lock. Physics, patience, patience.",
    totalPacks: 50,
    remainingPacks: 36,
    pricePerPack: 4.0,
    totalVolume: 16,
    salesCount: 2,
    nftTrades: 0,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(565),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "18w ago" },
    ],
  },
  {
    id: "ds077",
    title: "Radio Silence",
    creator: "@deepdesert",
    coverImageUrl: COVER_IMAGES[0],
    description:
      "Seven days in the empty quarter. No signal, no people, no noise.",
    totalPacks: 35,
    remainingPacks: 22,
    pricePerPack: 5.0,
    totalVolume: 14,
    salesCount: 1,
    nftTrades: 1,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(580),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 5.0, timeAgo: "19w ago" },
    ],
  },
  {
    id: "ds078",
    title: "Calligraphy Class",
    creator: "@strokeframe",
    coverImageUrl: COVER_IMAGES[3],
    description:
      "Traditional calligraphy class, Istanbul. Ink, silence, the loaded brush.",
    totalPacks: 55,
    remainingPacks: 40,
    pricePerPack: 3.5,
    totalVolume: 12,
    salesCount: 1,
    nftTrades: 0,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(595),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "20w ago" },
    ],
  },
  {
    id: "ds079",
    title: "Glass Blowing",
    creator: "@moltenframe",
    coverImageUrl: COVER_IMAGES[4],
    description:
      "Murano glass blowing. The gather, the blow, the collapse into form.",
    totalPacks: 45,
    remainingPacks: 33,
    pricePerPack: 4.5,
    totalVolume: 10,
    salesCount: 1,
    nftTrades: 0,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(610),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 4.5, timeAgo: "21w ago" },
    ],
  },
  {
    id: "ds080",
    title: "Monsoon Street",
    creator: "@rainframe.in",
    coverImageUrl: COVER_IMAGES[1],
    description:
      "Mumbai monsoon. Shoes off, streets as rivers, joy in the downpour.",
    totalPacks: 60,
    remainingPacks: 46,
    pricePerPack: 3.5,
    totalVolume: 9,
    salesCount: 1,
    nftTrades: 0,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(625),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "21w ago" },
    ],
  },
  {
    id: "ds081",
    title: "Night Garden",
    creator: "@moonflower",
    coverImageUrl: COVER_IMAGES[5],
    description:
      "A garden photographed only after dark. Flash, ambient, moonlight.",
    totalPacks: 50,
    remainingPacks: 38,
    pricePerPack: 4.0,
    totalVolume: 8,
    salesCount: 1,
    nftTrades: 0,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(640),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "22w ago" },
    ],
  },
  {
    id: "ds082",
    title: "Salt Mine",
    creator: "@underframe",
    coverImageUrl: COVER_IMAGES[0],
    description:
      "700m underground in a salt mine. Pink salt, old crystal, absolute quiet.",
    totalPacks: 40,
    remainingPacks: 30,
    pricePerPack: 5.0,
    totalVolume: 8,
    salesCount: 1,
    nftTrades: 0,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(655),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 5.0, timeAgo: "22w ago" },
    ],
  },
  {
    id: "ds083",
    title: "Waiting Room",
    creator: "@holdingframe",
    coverImageUrl: COVER_IMAGES[3],
    description: "Hospital waiting room, 6pm. Nine frames of suspended time.",
    totalPacks: 55,
    remainingPacks: 44,
    pricePerPack: 3.5,
    totalVolume: 7,
    salesCount: 1,
    nftTrades: 0,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(670),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "23w ago" },
    ],
  },
  {
    id: "ds084",
    title: "Abandoned Hotel",
    creator: "@decayframe",
    coverImageUrl: COVER_IMAGES[6],
    description:
      "A grand hotel, closed 1987. Ballroom, guest book, the last reservation.",
    totalPacks: 45,
    remainingPacks: 35,
    pricePerPack: 4.5,
    totalVolume: 7,
    salesCount: 1,
    nftTrades: 0,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(685),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 4.5, timeAgo: "24w ago" },
    ],
  },
  {
    id: "ds085",
    title: "Paper Mill",
    creator: "@pulpstudio",
    coverImageUrl: COVER_IMAGES[4],
    description:
      "The last hand paper mill in Wales. Rag to sheet, beginning to end.",
    totalPacks: 50,
    remainingPacks: 40,
    pricePerPack: 4.0,
    totalVolume: 6,
    salesCount: 1,
    nftTrades: 0,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(700),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "25w ago" },
    ],
  },
  {
    id: "ds086",
    title: "Lighthouse Beam",
    creator: "@signalframe",
    coverImageUrl: COVER_IMAGES[6],
    description:
      "Inside a working lighthouse. The Fresnel lens, the keeper, the beam.",
    totalPacks: 40,
    remainingPacks: 31,
    pricePerPack: 5.0,
    totalVolume: 6,
    salesCount: 1,
    nftTrades: 0,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(715),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 5.0, timeAgo: "25w ago" },
    ],
  },
  {
    id: "ds087",
    title: "Seed Library",
    creator: "@arkivframe",
    coverImageUrl: COVER_IMAGES[5],
    description:
      "The Svalbard Global Seed Vault. The most important archive on Earth.",
    totalPacks: 55,
    remainingPacks: 46,
    pricePerPack: 4.0,
    totalVolume: 5,
    salesCount: 1,
    nftTrades: 0,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(730),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "26w ago" },
    ],
  },
  {
    id: "ds088",
    title: "Sand Dune",
    creator: "@desertframe",
    coverImageUrl: COVER_IMAGES[0],
    description:
      "Saharan dunes at first light. Form, shadow, and wind in slow sculpture.",
    totalPacks: 65,
    remainingPacks: 55,
    pricePerPack: 3.5,
    totalVolume: 5,
    salesCount: 1,
    nftTrades: 0,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(745),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "27w ago" },
    ],
  },
  {
    id: "ds089",
    title: "Rainy Overpass",
    creator: "@drippingframe",
    coverImageUrl: COVER_IMAGES[1],
    description:
      "Underpass in heavy rain. Acoustic drip, dim fluorescent, the patience of waiting.",
    totalPacks: 45,
    remainingPacks: 37,
    pricePerPack: 4.0,
    totalVolume: 4,
    salesCount: 1,
    nftTrades: 0,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(760),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 4.0, timeAgo: "27w ago" },
    ],
  },
  {
    id: "ds090",
    title: "Spring Thaw",
    creator: "@meltframe",
    coverImageUrl: COVER_IMAGES[2],
    description:
      "Ice breaking up on a northern river. The sound of the season changing.",
    totalPacks: 60,
    remainingPacks: 50,
    pricePerPack: 3.5,
    totalVolume: 4,
    salesCount: 1,
    nftTrades: 0,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(775),
    recentSales: [
      { itemTitle: "Pack sold", priceUsd: 3.5, timeAgo: "28w ago" },
    ],
  },
  {
    id: "ds091",
    title: "Coppice Wood",
    creator: "@ancientframe",
    coverImageUrl: COVER_IMAGES[7],
    description:
      "Traditional coppice woodland management. Tools unchanged for centuries.",
    totalPacks: 50,
    remainingPacks: 42,
    pricePerPack: 4.0,
    totalVolume: 3,
    salesCount: 0,
    nftTrades: 1,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(790),
    recentSales: [{ itemTitle: "NFT trade", priceUsd: 12, timeAgo: "28w ago" }],
  },
  {
    id: "ds092",
    title: "Night Shift",
    creator: "@graveshift",
    coverImageUrl: COVER_IMAGES[6],
    description:
      "Security guard, 3am, an empty office building. Quiet as a held breath.",
    totalPacks: 40,
    remainingPacks: 34,
    pricePerPack: 4.5,
    totalVolume: 3,
    salesCount: 0,
    nftTrades: 1,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(805),
    recentSales: [{ itemTitle: "NFT trade", priceUsd: 14, timeAgo: "29w ago" }],
  },
  {
    id: "ds093",
    title: "Stone Circle",
    creator: "@megalith",
    coverImageUrl: COVER_IMAGES[0],
    description:
      "Rollright Stones at winter solstice. 4000 years of alignment, still accurate.",
    totalPacks: 55,
    remainingPacks: 48,
    pricePerPack: 4.0,
    totalVolume: 2,
    salesCount: 0,
    nftTrades: 1,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(820),
    recentSales: [{ itemTitle: "NFT trade", priceUsd: 11, timeAgo: "30w ago" }],
  },
  {
    id: "ds094",
    title: "Velodrome Sprint",
    creator: "@trackframe",
    coverImageUrl: COVER_IMAGES[3],
    description:
      "Track cycling velodrome. The banking, the scream of the crowd, the sprint.",
    totalPacks: 45,
    remainingPacks: 39,
    pricePerPack: 4.5,
    totalVolume: 2,
    salesCount: 0,
    nftTrades: 1,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(835),
    recentSales: [{ itemTitle: "NFT trade", priceUsd: 10, timeAgo: "30w ago" }],
  },
  {
    id: "ds095",
    title: "Bamboo Grove",
    creator: "@zenframe",
    coverImageUrl: COVER_IMAGES[7],
    description:
      "Arashiyama bamboo grove, 6am, before the crowds. Green vertical infinity.",
    totalPacks: 60,
    remainingPacks: 54,
    pricePerPack: 3.5,
    totalVolume: 2,
    salesCount: 0,
    nftTrades: 1,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(850),
    recentSales: [{ itemTitle: "NFT trade", priceUsd: 9, timeAgo: "31w ago" }],
  },
  {
    id: "ds096",
    title: "Coal Bunker",
    creator: "@lastlight.coal",
    coverImageUrl: COVER_IMAGES[3],
    description:
      "The last working coal mine in England, final week. Memory, dust, dignity.",
    totalPacks: 40,
    remainingPacks: 35,
    pricePerPack: 5.0,
    totalVolume: 1,
    salesCount: 0,
    nftTrades: 0,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(865),
    recentSales: [],
  },
  {
    id: "ds097",
    title: "Snowplow Night",
    creator: "@clearingframe",
    coverImageUrl: COVER_IMAGES[6],
    description:
      "Following a snowplow through the night. The essential invisible work.",
    totalPacks: 50,
    remainingPacks: 45,
    pricePerPack: 4.0,
    totalVolume: 1,
    salesCount: 0,
    nftTrades: 0,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(880),
    recentSales: [],
  },
  {
    id: "ds098",
    title: "Open Sea",
    creator: "@bluewater",
    coverImageUrl: COVER_IMAGES[2],
    description:
      "Three days at sea, no land visible. Nine frames of pure horizon.",
    totalPacks: 55,
    remainingPacks: 51,
    pricePerPack: 4.0,
    totalVolume: 1,
    salesCount: 0,
    nftTrades: 0,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(895),
    recentSales: [],
  },
  {
    id: "ds099",
    title: "Printing Press",
    creator: "@pressroom",
    coverImageUrl: COVER_IMAGES[4],
    description:
      "The Gutenberg press at the printing museum, still operational. Ink, type, paper.",
    totalPacks: 45,
    remainingPacks: 42,
    pricePerPack: 4.5,
    totalVolume: 1,
    salesCount: 0,
    nftTrades: 0,
    uniqueCollectors: 1,
    listedAt: daysAgoMs(910),
    recentSales: [],
  },
  {
    id: "ds100",
    title: "New Release",
    creator: "@freshstudio",
    coverImageUrl: COVER_IMAGES[5],
    description: "Just minted. A set with no history yet, just potential.",
    totalPacks: 100,
    remainingPacks: 100,
    pricePerPack: 3.0,
    totalVolume: 0,
    salesCount: 0,
    nftTrades: 0,
    uniqueCollectors: 0,
    listedAt: hoursAgoMs(1),
    recentSales: [],
  },
];

const TIME_RANGE_MS: Record<string, number> = {
  "24H": 24 * 60 * 60 * 1000,
  "7D": 7 * 24 * 60 * 60 * 1000,
  "30D": 30 * 24 * 60 * 60 * 1000,
};

export function getDiscoverSets(
  timeRange: "ALL_TIME" | "24H" | "7D" | "30D",
): MintMomentSetRank[] {
  const nowMs = Date.now();
  const cutoff =
    timeRange === "ALL_TIME"
      ? null
      : new Date(nowMs - TIME_RANGE_MS[timeRange]);

  const filtered = cutoff
    ? MOCK_DISCOVER_SETS.filter((s) => s.listedAt >= cutoff.getTime())
    : MOCK_DISCOVER_SETS;

  return [...filtered]
    .sort((a, b) => computeScore(b, nowMs) - computeScore(a, nowMs))
    .slice(0, 100);
}
