/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
}
export interface Collectible {
    id: string;
    setName: string;
    title: string;
    creator: string;
    typeSupply: bigint;
    editionNumber: bigint;
    ownerPrincipal: Principal;
    mintDate: string;
    totalSupply: bigint;
    imageUrl: string;
    releaseId: string;
    mediaType: CollectibleMediaType;
    rarity: string;
    packId: string;
    openedAt: bigint;
}
export interface TcgSet {
    id: bigint;
    setCode: string;
    coverImageUrl: string;
    setName: string;
    featured: boolean;
    tcgCategory: string;
    sortOrder: bigint;
    slug: string;
    isActive: boolean;
    cardCount?: bigint;
    releaseYear: bigint;
}
export interface MarketCapEntry {
    clipId: string;
    title: string;
    previewUrl: string;
    totalSupply: bigint;
    creatorName: string;
    currentPriceUsd: number;
    copiesSold: bigint;
    videoUrl: string;
    marketCapUsd: number;
}
export interface VideoAsset {
    owner: Principal;
    data: Uint8Array;
    content_type: string;
    created_at: bigint;
    asset_id: string;
}
export interface CreateTcgSetInput {
    setCode: string;
    coverImageUrl: string;
    setName: string;
    featured: boolean;
    tcgCategory: string;
    sortOrder: bigint;
    slug: string;
    isActive: boolean;
    cardCount?: bigint;
    releaseYear: bigint;
}
export interface CreateTcgCardInput {
    cardName: string;
    sortOrder: bigint;
    isActive: boolean;
    setId: bigint;
    imageUrl: string;
    rarity: string;
    cardNumber: string;
    isSupported: boolean;
}
export interface Transaction {
    id: bigint;
    status: string;
    clipId: string;
    totalUsd: number;
    timestamp: bigint;
    txType: TxType;
    splits: Array<TxSplit>;
}
export interface TxSplit {
    principal: Principal;
    role: string;
    usdAmount: number;
    btcAmountSimulated: number;
    btcAddress: string;
}
export interface Release {
    album: Album;
    floorPrice: bigint;
    isActive: boolean;
    lastSoldPrice: bigint;
    mintedCount: bigint;
    ownersCount: bigint;
    mintOpenTime: bigint;
}
export interface Album {
    id: string;
    coverImageUrl: string;
    title: string;
    tracklist: Array<Track>;
    totalSupply: bigint;
    artist: string;
    collectionName: string;
}
export interface PricePoint {
    editionNumber: bigint;
    timestamp: bigint;
    salePrice: number;
}
export type LikeResult = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "alreadyLiked";
    alreadyLiked: null;
} | {
    __kind__: "notFound";
    notFound: null;
};
export interface Track {
    title: string;
    duration: bigint;
}
export interface MarketListing {
    seller: Principal;
    editionId: bigint;
    price: bigint;
}
export interface Listing {
    id: bigint;
    status: ListingStatus;
    clipId: string;
    totalEditions: bigint;
    sellerPrincipal: Principal;
    listPriceUsd: number;
    editionNumber: bigint;
    listedAt: bigint;
}
export interface VideoClip {
    clip_id: string;
    like_timestamps: Array<[Principal, bigint]>;
    title?: string;
    hashtags: Array<string>;
    preview_loop_url: string;
    like_count: bigint;
    likes_last_6_hours: bigint;
    likes_last_24_hours: bigint;
    timestamp: bigint;
    likes_last_hour: bigint;
    explicit_flag: boolean;
    creator_principal_id: Principal;
    video_file_url: string;
}
export interface UpdateTcgCardInput {
    id: bigint;
    cardName: string;
    sortOrder: bigint;
    isActive: boolean;
    setId: bigint;
    imageUrl: string;
    rarity: string;
    cardNumber: string;
    isSupported: boolean;
}
export interface CreateTcgCategoryInput {
    sortOrder: bigint;
    name: string;
    slug: string;
    isActive: boolean;
    imageUrl: string;
}
export interface UpdateTcgCategoryInput {
    id: bigint;
    sortOrder: bigint;
    name: string;
    slug: string;
    isActive: boolean;
    imageUrl: string;
}
export interface UpdateTcgSetInput {
    id: bigint;
    setCode: string;
    coverImageUrl: string;
    setName: string;
    featured: boolean;
    tcgCategory: string;
    sortOrder: bigint;
    slug: string;
    isActive: boolean;
    cardCount?: bigint;
    releaseYear: bigint;
}
export interface TcgCard {
    id: bigint;
    cardName: string;
    sortOrder: bigint;
    isActive: boolean;
    setId: bigint;
    imageUrl: string;
    rarity: string;
    cardNumber: string;
    isSupported: boolean;
}
export interface Offer {
    id: bigint;
    status: OfferStatus;
    offerPriceUsd: number;
    listingId: bigint;
    createdAt: bigint;
    buyerPrincipal: Principal;
}
export interface Pack {
    id: string;
    status: PackStatus;
    coverImageUrl: string;
    setName: string;
    ownerPrincipal: Principal;
    createdAt: bigint;
    totalSupply: bigint;
    releaseId: string;
    serialNumber: bigint;
    packCount: bigint;
    collectibleId?: string;
    openedAt?: bigint;
}
export interface AddPackInput {
    id: string;
    coverImageUrl: string;
    setName: string;
    ownerPrincipal: Principal;
    totalSupply: bigint;
    releaseId: string;
    serialNumber: bigint;
    packCount: bigint;
}
export type PackOpenResult = {
    __kind__: "ok";
    ok: Collectible;
} | {
    __kind__: "err";
    err: string;
};
export interface TcgCategory {
    id: bigint;
    sortOrder: bigint;
    name: string;
    slug: string;
    isActive: boolean;
    imageUrl: string;
}
export enum CollectibleMediaType {
    video = "video",
    photo = "photo"
}
export enum ListingStatus {
    active = "active",
    cancelled = "cancelled",
    sold = "sold"
}
export enum OfferStatus {
    pending = "pending",
    accepted = "accepted",
    declined = "declined"
}
export enum PackStatus {
    opened = "opened",
    sealed = "sealed"
}
export enum TxType {
    mintFee = "mintFee",
    secondaryTrade = "secondaryTrade",
    copySale = "copySale"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VideoClipSort {
    top = "top",
    trending = "trending",
    newest = "newest"
}
export interface backendInterface {
    acceptOffer(offerId: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addAlbum(album: Album): Promise<void>;
    addPack(input: AddPackInput): Promise<void>;
    addRelease(release: Release): Promise<void>;
    assignRole(user: Principal, role: UserRole): Promise<void>;
    cancelListing(listingId: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createCard(input: CreateTcgCardInput): Promise<TcgCard>;
    createCategory(input: CreateTcgCategoryInput): Promise<TcgCategory>;
    /**
     * / Create a new video clip post. Returns the generated clip_id.
     */
    createClip(video_file_url: string, preview_loop_url: string, title: string | null, hashtags: Array<string>, explicit_flag: boolean): Promise<string>;
    createListing(clipId: string, editionNumber: bigint, listPriceUsd: number): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createSet(input: CreateTcgSetInput): Promise<TcgSet>;
    declineOffer(offerId: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteCard(id: bigint): Promise<void>;
    deleteCategory(id: bigint): Promise<void>;
    deleteSet(id: bigint): Promise<void>;
    getAlbumById(id: string): Promise<Album | null>;
    getAlbums(): Promise<Array<Album>>;
    getAllCardsAdmin(): Promise<Array<TcgCard>>;
    getAllCategoriesAdmin(): Promise<Array<TcgCategory>>;
    getAllSetsAdmin(): Promise<Array<TcgSet>>;
    getCallerCollectibles(): Promise<Array<Collectible>>;
    getCallerPacks(): Promise<Array<Pack>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCardsBySet(setId: bigint): Promise<Array<TcgCard>>;
    getCardsBySetAdmin(setId: bigint): Promise<Array<TcgCard>>;
    getCategories(): Promise<Array<TcgCategory>>;
    /**
     * / Fetch clips sorted by newest, trending (viral score), or top (total likes).
     * / safeView=true hides explicit clips.
     */
    getClips(sortBy: VideoClipSort, safeView: boolean): Promise<Array<VideoClip>>;
    /**
     * / Fetch clips filtered to a specific hashtag.
     * / Delegates to getClipsForHashtag with newest sort and no safe view filter.
     */
    getClipsByHashtag(hashtag: string): Promise<Array<VideoClip>>;
    /**
     * / Fetch clips filtered to a specific hashtag (case-insensitive), then sorted.
     */
    getClipsForHashtag(hashtag: string, sortBy: VideoClipSort, safeView: boolean): Promise<Array<VideoClip>>;
    /**
     * / Get all clips created by a specific principal.
     */
    getCreatorClips(creator: Principal): Promise<Array<VideoClip>>;
    getCurrentPrice(clipId: string): Promise<number>;
    getFeaturedSets(): Promise<Array<TcgSet>>;
    getListings(): Promise<Array<Listing>>;
    getListingsByClip(clipId: string): Promise<Array<Listing>>;
    getMarketCap(clipId: string): Promise<MarketCapEntry | null>;
    getMarketListings(): Promise<Array<MarketListing>>;
    getMyRole(): Promise<UserRole>;
    /**
     * / Returns transactions where p appears in any split's principal.
     */
    getMyTransactions(p: Principal): Promise<Array<Transaction>>;
    getOfferHistory(listingId: bigint): Promise<Array<Offer>>;
    getOffers(listingId: bigint): Promise<{
        __kind__: "ok";
        ok: Array<Offer>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getPokemonSets(): Promise<Array<TcgSet>>;
    getPriceHistory(clipId: string): Promise<Array<PricePoint>>;
    getReleases(): Promise<Array<Release>>;
    getSetById(id: bigint): Promise<TcgSet | null>;
    getSetBySlug(slug: string): Promise<TcgSet | null>;
    getSets(): Promise<Array<TcgSet>>;
    getSetsByCategory(categorySlug: string): Promise<Array<TcgSet>>;
    getTop10ByMarketCap(): Promise<Array<MarketCapEntry>>;
    /**
     * / Returns all transactions newest-first.
     */
    getTransactionHistory(): Promise<Array<Transaction>>;
    /**
     * / Get trending hashtags sorted by viral score descending.
     * / Returns (tag, post_count) pairs.
     */
    getTrendingHashtags(): Promise<Array<[string, bigint]>>;
    /**
     * / Get trending hashtags with a hot flag.
     * / Returns (tag, post_count, is_hot) — is_hot is true for tags in the top 3 by viral score.
     */
    getTrendingHashtagsWithHotFlag(): Promise<Array<[string, bigint, boolean]>>;
    getUserCollectibles(user: Principal): Promise<Array<Collectible>>;
    getUserPacks(user: Principal): Promise<Array<Pack>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    /**
     * / Retrieve raw video/preview blob data by asset_id.
     */
    getVideoBlob(asset_id: string): Promise<VideoAsset | null>;
    isAdmin(): Promise<boolean>;
    /**
     * / Like a clip. Each caller can only like once. Returns new like_count.
     */
    likeClip(clip_id: string): Promise<LikeResult>;
    makeOffer(listingId: bigint, offerPriceUsd: number): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    openPack(packId: string): Promise<PackOpenResult>;
    /**
     * / Record a $1 mint fee. 100% to platform wallet.
     */
    processClipMint(creatorPrincipal: Principal): Promise<bigint>;
    /**
     * / Record a bonding curve copy sale. 95% to creator, 5% to platform.
     */
    processCopySale(clipId: string, creatorPrincipal: Principal, buyerPrincipal: Principal, usdAmount: number): Promise<bigint>;
    /**
     * / Record a secondary trade. 4% to original creator, 1% to platform, 95% to seller.
     */
    processSecondaryTrade(clipId: string, originalCreatorPrincipal: Principal, sellerPrincipal: Principal, buyerPrincipal: Principal, usdAmount: number): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchSetsByName(searchTerm: string): Promise<Array<TcgSet>>;
    toggleCardActive(id: bigint): Promise<void>;
    toggleCardSupported(id: bigint): Promise<void>;
    toggleCategoryActive(id: bigint): Promise<void>;
    toggleSetActive(id: bigint): Promise<void>;
    updateCard(input: UpdateTcgCardInput): Promise<TcgCard>;
    updateCategory(input: UpdateTcgCategoryInput): Promise<TcgCategory>;
    updateSet(input: UpdateTcgSetInput): Promise<TcgSet>;
    /**
     * / Upload a raw preview clip blob (short 2s muted mp4). Returns asset_id to use as preview_loop_url.
     */
    uploadPreviewBlob(data: Uint8Array, content_type: string): Promise<string>;
    /**
     * / Upload a raw HD video blob (mp4). Returns asset_id to use as video_file_url.
     */
    uploadVideoBlob(data: Uint8Array, content_type: string): Promise<string>;
}
import type { Album as _Album, Collectible as _Collectible, CollectibleMediaType as _CollectibleMediaType, CreateTcgSetInput as _CreateTcgSetInput, LikeResult as _LikeResult, Listing as _Listing, ListingStatus as _ListingStatus, MarketCapEntry as _MarketCapEntry, Offer as _Offer, OfferStatus as _OfferStatus, Pack as _Pack, PackOpenResult as _PackOpenResult, PackStatus as _PackStatus, TcgSet as _TcgSet, Transaction as _Transaction, TxSplit as _TxSplit, TxType as _TxType, UpdateTcgSetInput as _UpdateTcgSetInput, UserProfile as _UserProfile, UserRole as _UserRole, VideoAsset as _VideoAsset, VideoClip as _VideoClip, VideoClipSort as _VideoClipSort } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acceptOffer(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptOffer(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptOffer(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addAlbum(arg0: Album): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAlbum(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAlbum(arg0);
            return result;
        }
    }
    async addPack(arg0: AddPackInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPack(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPack(arg0);
            return result;
        }
    }
    async addRelease(arg0: Release): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRelease(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRelease(arg0);
            return result;
        }
    }
    async assignRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelListing(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelListing(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelListing(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCard(arg0: CreateTcgCardInput): Promise<TcgCard> {
        if (this.processError) {
            try {
                const result = await this.actor.createCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCard(arg0);
            return result;
        }
    }
    async createCategory(arg0: CreateTcgCategoryInput): Promise<TcgCategory> {
        if (this.processError) {
            try {
                const result = await this.actor.createCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCategory(arg0);
            return result;
        }
    }
    async createClip(arg0: string, arg1: string, arg2: string | null, arg3: Array<string>, arg4: boolean): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createClip(arg0, arg1, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClip(arg0, arg1, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async createListing(arg0: string, arg1: bigint, arg2: number): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(arg0, arg1, arg2);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(arg0, arg1, arg2);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSet(arg0: CreateTcgSetInput): Promise<TcgSet> {
        if (this.processError) {
            try {
                const result = await this.actor.createSet(to_candid_CreateTcgSetInput_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_TcgSet_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSet(to_candid_CreateTcgSetInput_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_TcgSet_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async declineOffer(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.declineOffer(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.declineOffer(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCard(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCard(arg0);
            return result;
        }
    }
    async deleteCategory(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteSet(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSet(arg0);
            return result;
        }
    }
    async getAlbumById(arg0: string): Promise<Album | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlbumById(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlbumById(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAlbums(): Promise<Array<Album>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlbums();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlbums();
            return result;
        }
    }
    async getAllCardsAdmin(): Promise<Array<TcgCard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCardsAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCardsAdmin();
            return result;
        }
    }
    async getAllCategoriesAdmin(): Promise<Array<TcgCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCategoriesAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCategoriesAdmin();
            return result;
        }
    }
    async getAllSetsAdmin(): Promise<Array<TcgSet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSetsAdmin();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSetsAdmin();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerCollectibles(): Promise<Array<Collectible>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerCollectibles();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerCollectibles();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerPacks(): Promise<Array<Pack>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPacks();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPacks();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCardsBySet(arg0: bigint): Promise<Array<TcgCard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCardsBySet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCardsBySet(arg0);
            return result;
        }
    }
    async getCardsBySetAdmin(arg0: bigint): Promise<Array<TcgCard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCardsBySetAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCardsBySetAdmin(arg0);
            return result;
        }
    }
    async getCategories(): Promise<Array<TcgCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getClips(arg0: VideoClipSort, arg1: boolean): Promise<Array<VideoClip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClips(to_candid_VideoClipSort_n26(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClips(to_candid_VideoClipSort_n26(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClipsByHashtag(arg0: string): Promise<Array<VideoClip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClipsByHashtag(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClipsByHashtag(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClipsForHashtag(arg0: string, arg1: VideoClipSort, arg2: boolean): Promise<Array<VideoClip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClipsForHashtag(arg0, to_candid_VideoClipSort_n26(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClipsForHashtag(arg0, to_candid_VideoClipSort_n26(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCreatorClips(arg0: Principal): Promise<Array<VideoClip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreatorClips(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreatorClips(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentPrice(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentPrice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentPrice(arg0);
            return result;
        }
    }
    async getFeaturedSets(): Promise<Array<TcgSet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedSets();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedSets();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListings();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListings();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListingsByClip(arg0: string): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingsByClip(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingsByClip(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketCap(arg0: string): Promise<MarketCapEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketCap(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketCap(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketListings(): Promise<Array<MarketListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketListings();
            return result;
        }
    }
    async getMyRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRole();
                return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRole();
            return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTransactions(arg0: Principal): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTransactions(arg0);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTransactions(arg0);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOfferHistory(arg0: bigint): Promise<Array<Offer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOfferHistory(arg0);
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOfferHistory(arg0);
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOffers(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: Array<Offer>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getOffers(arg0);
                return from_candid_variant_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOffers(arg0);
            return from_candid_variant_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPokemonSets(): Promise<Array<TcgSet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPokemonSets();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPokemonSets();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPriceHistory(arg0: string): Promise<Array<PricePoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPriceHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPriceHistory(arg0);
            return result;
        }
    }
    async getReleases(): Promise<Array<Release>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReleases();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReleases();
            return result;
        }
    }
    async getSetById(arg0: bigint): Promise<TcgSet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSetById(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSetById(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSetBySlug(arg0: string): Promise<TcgSet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSetBySlug(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSetBySlug(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSets(): Promise<Array<TcgSet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSets();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSets();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSetsByCategory(arg0: string): Promise<Array<TcgSet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSetsByCategory(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSetsByCategory(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTop10ByMarketCap(): Promise<Array<MarketCapEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTop10ByMarketCap();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTop10ByMarketCap();
            return result;
        }
    }
    async getTransactionHistory(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionHistory();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionHistory();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrendingHashtags(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingHashtags();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingHashtags();
            return result;
        }
    }
    async getTrendingHashtagsWithHotFlag(): Promise<Array<[string, bigint, boolean]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingHashtagsWithHotFlag();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingHashtagsWithHotFlag();
            return result;
        }
    }
    async getUserCollectibles(arg0: Principal): Promise<Array<Collectible>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserCollectibles(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserCollectibles(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPacks(arg0: Principal): Promise<Array<Pack>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPacks(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPacks(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoBlob(arg0: string): Promise<VideoAsset | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoBlob(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoBlob(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async likeClip(arg0: string): Promise<LikeResult> {
        if (this.processError) {
            try {
                const result = await this.actor.likeClip(arg0);
                return from_candid_LikeResult_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeClip(arg0);
            return from_candid_LikeResult_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async makeOffer(arg0: bigint, arg1: number): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.makeOffer(arg0, arg1);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.makeOffer(arg0, arg1);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async openPack(arg0: string): Promise<PackOpenResult> {
        if (this.processError) {
            try {
                const result = await this.actor.openPack(arg0);
                return from_candid_PackOpenResult_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.openPack(arg0);
            return from_candid_PackOpenResult_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async processClipMint(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.processClipMint(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processClipMint(arg0);
            return result;
        }
    }
    async processCopySale(arg0: string, arg1: Principal, arg2: Principal, arg3: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.processCopySale(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processCopySale(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async processSecondaryTrade(arg0: string, arg1: Principal, arg2: Principal, arg3: Principal, arg4: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.processSecondaryTrade(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processSecondaryTrade(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchSetsByName(arg0: string): Promise<Array<TcgSet>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchSetsByName(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchSetsByName(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleCardActive(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleCardActive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleCardActive(arg0);
            return result;
        }
    }
    async toggleCardSupported(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleCardSupported(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleCardSupported(arg0);
            return result;
        }
    }
    async toggleCategoryActive(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleCategoryActive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleCategoryActive(arg0);
            return result;
        }
    }
    async toggleSetActive(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleSetActive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleSetActive(arg0);
            return result;
        }
    }
    async updateCard(arg0: UpdateTcgCardInput): Promise<TcgCard> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCard(arg0);
            return result;
        }
    }
    async updateCategory(arg0: UpdateTcgCategoryInput): Promise<TcgCategory> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(arg0);
            return result;
        }
    }
    async updateSet(arg0: UpdateTcgSetInput): Promise<TcgSet> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSet(to_candid_UpdateTcgSetInput_n56(this._uploadFile, this._downloadFile, arg0));
                return from_candid_TcgSet_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSet(to_candid_UpdateTcgSetInput_n56(this._uploadFile, this._downloadFile, arg0));
            return from_candid_TcgSet_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadPreviewBlob(arg0: Uint8Array, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPreviewBlob(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPreviewBlob(arg0, arg1);
            return result;
        }
    }
    async uploadVideoBlob(arg0: Uint8Array, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadVideoBlob(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadVideoBlob(arg0, arg1);
            return result;
        }
    }
}
function from_candid_CollectibleMediaType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CollectibleMediaType): CollectibleMediaType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Collectible_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Collectible): Collectible {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_LikeResult_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LikeResult): LikeResult {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_ListingStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingStatus): ListingStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Listing_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Listing): Listing {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_OfferStatus_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OfferStatus): OfferStatus {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_Offer_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Offer): Offer {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_PackOpenResult_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PackOpenResult): PackOpenResult {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_PackStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PackStatus): PackStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Pack_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Pack): Pack {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_TcgSet_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TcgSet): TcgSet {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_TxType_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TxType): TxType {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_VideoClip_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoClip): VideoClip {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Album]): Album | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MarketCapEntry]): MarketCapEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TcgSet]): TcgSet | null {
    return value.length === 0 ? null : from_candid_TcgSet_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VideoAsset]): VideoAsset | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    setName: string;
    title: string;
    creator: string;
    typeSupply: bigint;
    editionNumber: bigint;
    ownerPrincipal: Principal;
    mintDate: string;
    totalSupply: bigint;
    imageUrl: string;
    releaseId: string;
    mediaType: _CollectibleMediaType;
    rarity: string;
    packId: string;
    openedAt: bigint;
}): {
    id: string;
    setName: string;
    title: string;
    creator: string;
    typeSupply: bigint;
    editionNumber: bigint;
    ownerPrincipal: Principal;
    mintDate: string;
    totalSupply: bigint;
    imageUrl: string;
    releaseId: string;
    mediaType: CollectibleMediaType;
    rarity: string;
    packId: string;
    openedAt: bigint;
} {
    return {
        id: value.id,
        setName: value.setName,
        title: value.title,
        creator: value.creator,
        typeSupply: value.typeSupply,
        editionNumber: value.editionNumber,
        ownerPrincipal: value.ownerPrincipal,
        mintDate: value.mintDate,
        totalSupply: value.totalSupply,
        imageUrl: value.imageUrl,
        releaseId: value.releaseId,
        mediaType: from_candid_CollectibleMediaType_n16(_uploadFile, _downloadFile, value.mediaType),
        rarity: value.rarity,
        packId: value.packId,
        openedAt: value.openedAt
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _PackStatus;
    coverImageUrl: string;
    setName: string;
    ownerPrincipal: Principal;
    createdAt: bigint;
    totalSupply: bigint;
    releaseId: string;
    serialNumber: bigint;
    packCount: bigint;
    collectibleId: [] | [string];
    openedAt: [] | [bigint];
}): {
    id: string;
    status: PackStatus;
    coverImageUrl: string;
    setName: string;
    ownerPrincipal: Principal;
    createdAt: bigint;
    totalSupply: bigint;
    releaseId: string;
    serialNumber: bigint;
    packCount: bigint;
    collectibleId?: string;
    openedAt?: bigint;
} {
    return {
        id: value.id,
        status: from_candid_PackStatus_n21(_uploadFile, _downloadFile, value.status),
        coverImageUrl: value.coverImageUrl,
        setName: value.setName,
        ownerPrincipal: value.ownerPrincipal,
        createdAt: value.createdAt,
        totalSupply: value.totalSupply,
        releaseId: value.releaseId,
        serialNumber: value.serialNumber,
        packCount: value.packCount,
        collectibleId: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.collectibleId)),
        openedAt: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.openedAt))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clip_id: string;
    like_timestamps: Array<[Principal, bigint]>;
    title: [] | [string];
    hashtags: Array<string>;
    preview_loop_url: string;
    like_count: bigint;
    likes_last_6_hours: bigint;
    likes_last_24_hours: bigint;
    timestamp: bigint;
    likes_last_hour: bigint;
    explicit_flag: boolean;
    creator_principal_id: Principal;
    video_file_url: string;
}): {
    clip_id: string;
    like_timestamps: Array<[Principal, bigint]>;
    title?: string;
    hashtags: Array<string>;
    preview_loop_url: string;
    like_count: bigint;
    likes_last_6_hours: bigint;
    likes_last_24_hours: bigint;
    timestamp: bigint;
    likes_last_hour: bigint;
    explicit_flag: boolean;
    creator_principal_id: Principal;
    video_file_url: string;
} {
    return {
        clip_id: value.clip_id,
        like_timestamps: value.like_timestamps,
        title: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.title)),
        hashtags: value.hashtags,
        preview_loop_url: value.preview_loop_url,
        like_count: value.like_count,
        likes_last_6_hours: value.likes_last_6_hours,
        likes_last_24_hours: value.likes_last_24_hours,
        timestamp: value.timestamp,
        likes_last_hour: value.likes_last_hour,
        explicit_flag: value.explicit_flag,
        creator_principal_id: value.creator_principal_id,
        video_file_url: value.video_file_url
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ListingStatus;
    clipId: string;
    totalEditions: bigint;
    sellerPrincipal: Principal;
    listPriceUsd: number;
    editionNumber: bigint;
    listedAt: bigint;
}): {
    id: bigint;
    status: ListingStatus;
    clipId: string;
    totalEditions: bigint;
    sellerPrincipal: Principal;
    listPriceUsd: number;
    editionNumber: bigint;
    listedAt: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ListingStatus_n34(_uploadFile, _downloadFile, value.status),
        clipId: value.clipId,
        totalEditions: value.totalEditions,
        sellerPrincipal: value.sellerPrincipal,
        listPriceUsd: value.listPriceUsd,
        editionNumber: value.editionNumber,
        listedAt: value.listedAt
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    clipId: string;
    totalUsd: number;
    timestamp: bigint;
    txType: _TxType;
    splits: Array<_TxSplit>;
}): {
    id: bigint;
    status: string;
    clipId: string;
    totalUsd: number;
    timestamp: bigint;
    txType: TxType;
    splits: Array<TxSplit>;
} {
    return {
        id: value.id,
        status: value.status,
        clipId: value.clipId,
        totalUsd: value.totalUsd,
        timestamp: value.timestamp,
        txType: from_candid_TxType_n42(_uploadFile, _downloadFile, value.txType),
        splits: value.splits
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OfferStatus;
    offerPriceUsd: number;
    listingId: bigint;
    createdAt: bigint;
    buyerPrincipal: Principal;
}): {
    id: bigint;
    status: OfferStatus;
    offerPriceUsd: number;
    listingId: bigint;
    createdAt: bigint;
    buyerPrincipal: Principal;
} {
    return {
        id: value.id,
        status: from_candid_OfferStatus_n47(_uploadFile, _downloadFile, value.status),
        offerPriceUsd: value.offerPriceUsd,
        listingId: value.listingId,
        createdAt: value.createdAt,
        buyerPrincipal: value.buyerPrincipal
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    setCode: string;
    coverImageUrl: string;
    setName: string;
    featured: boolean;
    tcgCategory: string;
    sortOrder: bigint;
    slug: string;
    isActive: boolean;
    cardCount: [] | [bigint];
    releaseYear: bigint;
}): {
    id: bigint;
    setCode: string;
    coverImageUrl: string;
    setName: string;
    featured: boolean;
    tcgCategory: string;
    sortOrder: bigint;
    slug: string;
    isActive: boolean;
    cardCount?: bigint;
    releaseYear: bigint;
} {
    return {
        id: value.id,
        setCode: value.setCode,
        coverImageUrl: value.coverImageUrl,
        setName: value.setName,
        featured: value.featured,
        tcgCategory: value.tcgCategory,
        sortOrder: value.sortOrder,
        slug: value.slug,
        isActive: value.isActive,
        cardCount: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.cardCount)),
        releaseYear: value.releaseYear
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    photo: null;
}): CollectibleMediaType {
    return "video" in value ? CollectibleMediaType.video : "photo" in value ? CollectibleMediaType.photo : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    opened: null;
} | {
    sealed: null;
}): PackStatus {
    return "opened" in value ? PackStatus.opened : "sealed" in value ? PackStatus.sealed : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    cancelled: null;
} | {
    sold: null;
}): ListingStatus {
    return "active" in value ? ListingStatus.active : "cancelled" in value ? ListingStatus.cancelled : "sold" in value ? ListingStatus.sold : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mintFee: null;
} | {
    secondaryTrade: null;
} | {
    copySale: null;
}): TxType {
    return "mintFee" in value ? TxType.mintFee : "secondaryTrade" in value ? TxType.secondaryTrade : "copySale" in value ? TxType.copySale : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    accepted: null;
} | {
    declined: null;
}): OfferStatus {
    return "pending" in value ? OfferStatus.pending : "accepted" in value ? OfferStatus.accepted : "declined" in value ? OfferStatus.declined : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Offer>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<Offer>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n44(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    alreadyLiked: null;
} | {
    notFound: null;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "alreadyLiked";
    alreadyLiked: null;
} | {
    __kind__: "notFound";
    notFound: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "alreadyLiked" in value ? {
        __kind__: "alreadyLiked",
        alreadyLiked: value.alreadyLiked
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Collectible;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Collectible;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Collectible_n14(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TcgSet>): Array<TcgSet> {
    return value.map((x)=>from_candid_TcgSet_n8(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Collectible>): Array<Collectible> {
    return value.map((x)=>from_candid_Collectible_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Pack>): Array<Pack> {
    return value.map((x)=>from_candid_Pack_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoClip>): Array<VideoClip> {
    return value.map((x)=>from_candid_VideoClip_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Listing>): Array<Listing> {
    return value.map((x)=>from_candid_Listing_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Offer>): Array<Offer> {
    return value.map((x)=>from_candid_Offer_n45(_uploadFile, _downloadFile, x));
}
function to_candid_CreateTcgSetInput_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateTcgSetInput): _CreateTcgSetInput {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateTcgSetInput_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateTcgSetInput): _UpdateTcgSetInput {
    return to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_VideoClipSort_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoClipSort): _VideoClipSort {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    setCode: string;
    coverImageUrl: string;
    setName: string;
    featured: boolean;
    tcgCategory: string;
    sortOrder: bigint;
    slug: string;
    isActive: boolean;
    cardCount?: bigint;
    releaseYear: bigint;
}): {
    id: bigint;
    setCode: string;
    coverImageUrl: string;
    setName: string;
    featured: boolean;
    tcgCategory: string;
    sortOrder: bigint;
    slug: string;
    isActive: boolean;
    cardCount: [] | [bigint];
    releaseYear: bigint;
} {
    return {
        id: value.id,
        setCode: value.setCode,
        coverImageUrl: value.coverImageUrl,
        setName: value.setName,
        featured: value.featured,
        tcgCategory: value.tcgCategory,
        sortOrder: value.sortOrder,
        slug: value.slug,
        isActive: value.isActive,
        cardCount: value.cardCount ? candid_some(value.cardCount) : candid_none(),
        releaseYear: value.releaseYear
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    setCode: string;
    coverImageUrl: string;
    setName: string;
    featured: boolean;
    tcgCategory: string;
    sortOrder: bigint;
    slug: string;
    isActive: boolean;
    cardCount?: bigint;
    releaseYear: bigint;
}): {
    setCode: string;
    coverImageUrl: string;
    setName: string;
    featured: boolean;
    tcgCategory: string;
    sortOrder: bigint;
    slug: string;
    isActive: boolean;
    cardCount: [] | [bigint];
    releaseYear: bigint;
} {
    return {
        setCode: value.setCode,
        coverImageUrl: value.coverImageUrl,
        setName: value.setName,
        featured: value.featured,
        tcgCategory: value.tcgCategory,
        sortOrder: value.sortOrder,
        slug: value.slug,
        isActive: value.isActive,
        cardCount: value.cardCount ? candid_some(value.cardCount) : candid_none(),
        releaseYear: value.releaseYear
    };
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoClipSort): {
    top: null;
} | {
    trending: null;
} | {
    newest: null;
} {
    return value == VideoClipSort.top ? {
        top: null
    } : value == VideoClipSort.trending ? {
        trending: null
    } : value == VideoClipSort.newest ? {
        newest: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
